### ISSUE TITLE
"move to opposite strand" should be available for features in the evidence area as well.

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#110]
Lengthier but clearer.   "move to opposite strand" should be available for features in the "evidence" area as well

**Comment by cmdcolin** [comment]
We had a short discussion during the meeting about how proper rendering of the paired-end alignments could go a ways towards fixing this problem. Reference: https://github.com/GMOD/jbrowse/pull/485

**Comment by monicacecilia** [comment]
Reviewed changes in GMOD/jbrowse#485 and they do not help in solving this. 

@enuggetry if you feel like taking a look at this for JBrowse, I think it would be very useful. 
This functionality would allow users to change the directionality of one read (one element) in an evidence track. This is useful, for example, when you want to use a read from an RNA-seq track as point of reference for modifying the boundaries in a genomic element you are annotating. 

Because this deals directly with display of features on JBrowse, I'm punting it out of here. :bowtie:
