### ISSUE TITLE
Last visited scaffold is no longer preserved across sessions.

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#1102]
Last visited scaffold is no longer preserved across sessions. Is this deliberate? Am I the only one seeing this? When I log out, then change window, and log back in with same UserName, I am being sent back to first available organism (i.e. Cat in _Staging_).

**Comment by nathandunn** [comment]
Not deliberate, definitely a bug.

**Comment by nathandunn** [comment]
For some reason, with no preferences set it is creating 3 almost identical entries, which means its not calculating the equality properly.

**Comment by nathandunn** [comment]
Fixed some things, but wanted to check off what is still problematic.

- [ ] on login 3 "preferences" set (not a big problem, but annoying)
- [ ] on logging back in, it picks up the organism correctly in the appState, but fails to update the browser for some reason 
- [ ] safari fails to create a clientToken . .  though otherwise works fine

**Comment by nathandunn** [comment]
I think we are good . . . rebuilding for test now .

**Comment by nathandunn** [comment]
@monicacecilia  I re-confirmed that this was working.  I had to blow on the preferences (and the annotations), but it looks correct.   However, it should probably look them up by lastUpdated.  Hmm . . .

**Comment by nathandunn** [comment]
By defalut they use the creation date, but if you go back and for it might get annoying

**Comment by nathandunn** [comment]
Okay . . this is fixed now (pushed tag).

**Comment by monicacecilia** [comment]
Yes, it *remembers* now. 💃
