### ISSUE TITLE
remove organism

### ISSUE THREAD

**Issue by lfaino** [GMOD/Apollo#1104]
Dear,
this is not a issue. I would like to know which is the easiest way of remove an organism from WebApollo. could you please help?

thanks
Luigi

**Comment by nathandunn** [comment]
Sure.  

If you have no annotations on an organism, then you should be able to go to the organism tab and hit delete. 

If you DO have annotations, you can delete them and then do a delete. 

Conversely, you can use web-services to do the same:

http://icebox.lbl.gov/Apollo2/WebServices/ <http://icebox.lbl.gov/Apollo2/WebServices/>

We have a working example script here (should be in your local doc directory):

https://github.com/GMOD/Apollo/blob/master/docs/web_services/examples/groovy/delete_annotations_from_organism.groovy <https://github.com/GMOD/Apollo/blob/master/docs/web_services/examples/groovy/delete_annotations_from_organism.groovy>

groovy delete_annotations_from_organism.groovy -organismname organism_name -destinationurl http://localhost:8080/Apollo

To run this directly you have to install groovy (probably using SDKMAN http://sdkman.io/install.html <http://sdkman.io/install.html> .  . .sdk install groovy)

We made this purposefully a bit more difficult so that folks wouldn’t accidentally nuke annotations.

Let us know if this works. 

Nathan

**Comment by lfaino** [comment]
Hi Nathan,
you are very quick. I do have an annotation and actually I would like to remove that and place a new one for the organism. however, I do not understand how to use the webservices. how can i set the user, password and organism from the WebSeevices? 

moreover, we I use the groovy script i get this error:

org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
General error during conversion: Error grabbing Grapes -- [unresolved dependency: org.codehaus.groovy.modules.http-builder#http-builder;0.7.2: not found]

thanks
Luigi

**Comment by nathandunn** [comment]
If you only have a single annotation (or just a few), I would just delete it by using the right-click menu and then delete the organism. 

If you have a large batch (like >20 . . .when it starts to become a pain) then this method should work. 




First of all, it shouldn’t be such a pain, by something is up with the way this resolves with maven.  Hopefully this will work. 

Change the top of your script, changing the version of http-builder from 0.7.2 to 0.5.2 (not sure why this works, but it does):

@Grab(group='org.codehaus.groovy.modules.http-builder', module='http-builder', version='0.5.2' )

If that doesn’t work you can try this advice as well, which is deleting the local cached grapes:   http://stackoverflow.com/a/24959124/1739366

rm -rf ~/.groovy/grapes 

and if that doesn’t work you can delete the local maven directory as well:

rm -rf ~/.m2  

And if THIS doesn’t work, you can edit your grapesConfig.xml (see the above stackOverflow) according to these instructions: 


I was able to confirm that it still worked after changing the version:

groovy delete_annotations_from_organism.groovy -organismname TestOrganism -destinationurl http://icebox.lbl.gov/Apollo2 -adminusername nathandunn@lbl.gov -adminpassword password

Worst-case, I can probably put together a shell script to do the same next week.  

Nathan

**Comment by lfaino** [comment]
Hi Nathan,
at the end it worked out. I had to update my groovy to 2.4.6 and change the httpbuilder to 0.5.2 and remove the folders.

thanks
Luigi

**Comment by nathandunn** [comment]
Glad it worked out!
