### ISSUE TITLE
allow for sequence download of a highlighted region

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1152]
We could do this in JBrowse, but probably easier than that would just be to add a menu (download highlighted region).

**Comment by nathandunn** [comment]
We can just add an option to this screen: 

<img width="450" alt="screen shot 2016-06-30 at 3 14 49 pm" src="https://cloud.githubusercontent.com/assets/751274/16501045/7478166a-3ed5-11e6-8c15-97f286548749.png">

**Comment by nathandunn** [comment]
For straight JBrowse this works over the reference sequence:  

<img width="846" alt="screen shot 2016-06-30 at 3 40 25 pm" src="https://cloud.githubusercontent.com/assets/751274/16501770/12a7e33a-3ed9-11e6-8e6b-e78abf5142c6.png">

**Comment by nathandunn** [comment]
However, if I add this to SequenceTrack, it only tries to pull annotated sequences, which is not what we want.

**Comment by nathandunn** [comment]
This code detects if there is a highlighted region:

```
        var highlightedRegion = this.browser.getHighlight();
        if( highlightedRegion ) {
            regions.unshift( lang.mixin( lang.clone( highlightedRegion ), { description: "Highlighted region", name: "highlight" } ) );
        }
```

**Comment by nathandunn** [comment]
We are just doing a regular export this way.  You have to be logged in:

<img width="593" alt="screen shot 2016-06-30 at 11 14 18 pm" src="https://cloud.githubusercontent.com/assets/751274/16510921/8b0fd65e-3f18-11e6-835a-fa66f2ee2130.png">
<img width="455" alt="screen shot 2016-06-30 at 11 14 31 pm" src="https://cloud.githubusercontent.com/assets/751274/16510920/8b0fd744-3f18-11e6-8407-9a67e868770d.png">

**Comment by nathandunn** [comment]
@monicacecilia  Can you review that this is okay.   Typically this was done on the sequence track, but that is not always visible.  At least with this change it is possible to do it, but you have to be logged in.

**Comment by nathandunn** [comment]
- [ ] change ```Highlighted Genome``` to ```Highlighted Region```

FYI @aswd

**Comment by nathandunn** [comment]
FYI @monicacecilia   notes on issue:  https://github.com/GMOD/Apollo/issues/1152#issuecomment-229975747

**Comment by nathandunn** [comment]
- [ ] is missing start by one

**Comment by nathandunn** [comment]
Is there more coming on this?

**Comment by monicacecilia** [comment]
yes. be patient. this is not ready.

**Comment by monicacecilia** [comment]
Well, something smells badly here. 

Steps I took: 
1. I highlighted a region using the button to the right of the 'Search' box in the main annotation panel.
2. I pulled the 'Save track data' menus to export FASTA from the highlighted region from 2a. _User-created Annotations_ area and from 2b. Automated predictions track (in this case OGSv3.2). 

Results:
- Error: When trying to obtain the FASTA file from the _'User-created Annotations'_ area (2a.) there is no definition line in the file we are generating. There should be a line describing the sequence, beginning with a caret (>), then the description, and the expected sequence below. 

- Error: When trying to retrieve either the _'genomic.fasta'_ or the _'peptide.fasta'_ files from the highlighted region using the right-click menu in the evidence track, the files looked exactly the same, and also without a definition line. The export process produced nucleotides without def line. 

- The genomic file of the highlighted region: 
![screen shot 2016-07-27 at 6 18 50 pm](https://cloud.githubusercontent.com/assets/1714621/17198009/9760d9b2-5426-11e6-912c-6a970ef26769.png)

- The peptide file of the highlighted region looks exactly the same as the genomic one. This is incorrect. There should be amino acid residues instead of nucleotide residues, and if there are more than one peptides in the highlighted region, they should be separated by carets + def line. Instead, this is what it looks like:
![screen shot 2016-07-27 at 6 19 31 pm](https://cloud.githubusercontent.com/assets/1714621/17198020/b0aae2e6-5426-11e6-8ec5-f29f6c1a5e4e.png)

- If I remove the highlight and try the same export, this peptide file looks as expected, like this: 
![screen shot 2016-07-27 at 6 17 25 pm](https://cloud.githubusercontent.com/assets/1714621/17198028/c7564184-5426-11e6-991c-538ff99d0b91.png)

**Comment by nathandunn** [comment]
- [ ] add defline to exported FASTA in the annotation track
- [ ] remove the 'FASTA' option from the Evidence tracks (that was an option that was added, but not completed, and should not have been in there)

**Comment by nathandunn** [comment]
@monicacecilia  I'm not entirely sure what this means:

> Error: When trying to retrieve either the 'genomic.fasta' or the 'peptide.fasta' files from the highlighted region using the right-click menu in the evidence track,

This is the only screen I see off of the evidence track: 

<img width="598" alt="screen shot 2016-07-28 at 6 53 36 am" src="https://cloud.githubusercontent.com/assets/751274/17214955/13a0917a-5490-11e6-8f61-f800ef3cd636.png">

**Comment by nathandunn** [comment]
exported sequences (from the UcA) now looks like this: 
<img width="542" alt="screen shot 2016-07-28 at 7 18 54 am" src="https://cloud.githubusercontent.com/assets/751274/17215992/b4c75e28-5493-11e6-8b23-ee2ea60ad8f3.png">

**Comment by monicacecilia** [comment]
@nathandunn That was my mistake. I was still talking about the 'Save track data' menu option in the Uc-A area. Here is that error explained again:

- Error: When trying to retrieve either the _genomic.fasta_, _peptide.fasta_, _cds.fasta_, or _cDNA.fasta_, files from the _User-created Annotations_ area, __while there is a highlighted region__, the four files looked exactly the same as just exporting the sequence using the 'highlighted region' menu option; also they do not have a definition line. The export process produced nucleotides without def line, even when amino acid residues were expected.

- This is the menu I am using to retrieve data: 
![screen shot 2016-07-28 at 9 20 46 am](https://cloud.githubusercontent.com/assets/1714621/17220638/f6835b08-54a4-11e6-8d9a-0520e945b6d2.png)

- As you can see, when a region is highlighted, ALL THE FILES EXPORT THE SAME DATA: 
![screen shot 2016-07-28 at 9 20 27 am](https://cloud.githubusercontent.com/assets/1714621/17220650/02f23382-54a5-11e6-970e-cb660fea42c4.png)

- The expected behavior is to see different files, with nucleotide or amino acid residues as appropriate, and with definition lines.

**Comment by nathandunn** [comment]
Gotcha.   The CDS, peptide, and cDNA should ignore the highlighted region and they are not.   I can fix.

**Comment by monicacecilia** [comment]
Correct. If there is an option to export data only from the highlighted region, then the other options should not be only from the highlighted region. That would be redundant. As it currently appears, we are exporting nucleotides when an amino acid sequence is expected. That is incorrect.

**Comment by monicacecilia** [comment]
Hooray! 💃
