### ISSUE TITLE
add user/organism-admin permission level

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1178]
Related to #771 and related to [this thread](http://comments.gmane.org/gmane.science.biology.gmod.apollo/1920).  

I think that the proposal would be to add another permission level between organism-admin (when you select a user as an admin for a single organism) and "write".  A super-admin would remain the same and be required to add users to groups (so super-admin,organism-admin,**user-admin**,write,export,read).  user-admin would be the new one.

Requirements for the new permission level:
- create users that are automatically assigned to an organism
- user tab would show up, but only those that share the organism that hey are a user-admin on 
- group tab would show up, but only those of the same group would be visible
- only the organisms available would show up, and would have minimal editable fields (if any)
- no global system permissions would be available
- reports would be available, but only for related organisms and users (this might be VERY messy, however)

**Comment by nathandunn** [comment]
Confluence permissions are fairly similar to our use-cases where a "space" is like an organism:

https://confluence.atlassian.com/doc/space-permissions-overview-139521.html

**Comment by mpoelchau** [comment]
@nathandunn:

At a first glance, I find the distinction between organism admin and user admin a bit confusing, but I understand why you're making that distinction - the organism admin in the current Apollo setup is simply a user with admin permissions for that organism, rather than the special set of permissions that we're discussing. Might be good to come up with a different name than user-admin (organism admin level 2? Also not great, just throwing things out there). 

I agree with the requirements that you describe above. It would also be nice if the user admin's permissions could be configured to some extent by the global admin. Here's what I came up with for the 'Admin' tab:

Canned Comments - default no access, but configurable by global admin
Canned Key - default no access, but configurable by global admin
Canned Values - default no access, but configurable by global admin
Feature Types - default no access, but configurable by global admin
Statuses - default no access, but configurable by global admin
Proxies - default no access, but configurable by global admin
Report::Organisms - restrict to organism that they are user admin for
Report::Sequences - restrict to organism that they are user admin for
Report::Annotator - restrict to organism that they are user admin for
Report::Changes - restrict to organism that they are user admin for
System Info - no access
Performance Metrics - default no access, but configurable by global admin
WebServices - default no access, but configurable by global admin

**Comment by nathandunn** [comment]
@mpoelchau   I think this sounds good (though WebServices (just documentation) is visible by all).  

Organism-manager or something like that probably makes sense.  Whoever adds it first gets to decide ;)

**Comment by Yating-L** [comment]
Organism admin is very close to what we want, except for some "extra" permissions. I am not sure if an organism admin should be allowed to do these:
- can see all the users sitewide, and delete them, even the global admin users
- can see all the groups, and delete them
- can add users to the groups that belong to another organism admin. In that case, the organism admin can add himself/herself to a group that can edit/view the other organisms.

The new role (instructor role) we'd like to have can do:
1. add an organism to Apollo 
1. overwrite or delete the organism he or she added
1. only access and have admin permission to the organisms he or she added
1. manage users: add / delete users, but cannot see or manipulate other instructors' users
1. create groups, add users to groups, but cannot access to other instructors' groups

**Comment by nathandunn** [comment]
@Yating-L  I think this sounds good.  I think we should just co-opt the organism admin, since the behavior you are outlining is largely the behavior most folks would expect.

**Comment by nathandunn** [comment]
@Yating-L  I think this is correct now.  The annotator report has to be for a global admin, but feel free to work with it (or create another one).  The Config.groovy contains the permissions.  

Let me know if this works and I can merge it.   Thanks.

**Comment by Yating-L** [comment]
@nathandunn this works. Thank you!

**Comment by nathandunn** [comment]
@Yating-L  It is review for review and test?

**Comment by nathandunn** [comment]
Oh, never mind, I see your response now.
