### ISSUE TITLE
Apollo URL containing feature location

### ISSUE THREAD

**Issue by mictadlo** [GMOD/Apollo#1279]
Hi, 
In JBrowse I can do `http://sefapps02.qut.edu.au/jaybrowse/?loc=Nbv0.5scaffold4111:167171..167678`, but in Apollo `http://203.101.228.52:8080/apollo/annotator/index/?loc=Nbv0.5scaffold4111:167171..167678` it does not work.

Is there a way to include in the URL the feature location?

Thank you in advance.

Mic

**Comment by nathandunn** [comment]
Yeah, you can use the "loadLink" URL.   You generate these by clicking on the link / chain icon but the pattern is pretty straight-forward (login demo@demo.com / demo).  

http://icebox.lbl.gov/Apollo2/annotator/loadLink?loc=Group1.1:117024..121400&organism=3836&tracks=Official%20Gene%20Set%20v3.2

Also, if you are in full-screen mode you can do stuff like this:

http://localhost:8080/apollo/Honeybee/jbrowse/index.html?loc=%7B%22description%22%3A%22GroupUn87%22%2C%20%22padding%22%3A0%2C%20%22sequenceList%22%3A%5B%7B%22name%22%3A%22GroupUn87%22%2C%20%22start%22%3A0%2C%20%22end%22%3A78258%2C%20%22reverse%22%3Afalse%7D%5D%7D%3A-1..-1%3A28579..30601%3A7810..70416%3A7810..70416&showFrame=false&tracklist=1&tracks=DNA%2CLegend%2CAnnotations%2COfficial%20Gene%20Set%20v3.2&highlight=&nav=1&overview=1

Go ahead and close it if those work.

**Comment by nathandunn** [comment]
@mictaldo  uhm, ignore my second example (off of some very beta code).  What I meant was that you can use something like this:  

http://icebox.lbl.gov/Apollo2/Honeybee/jbrowse/index.html?loc=Group1.1%3A117022..121398&tracks=DNA%2CAnnotations%2COfficial%20Gene%20Set%20v3.2&tracklist=1&highlight=&nav=1&overview=1

If you are adding dynamic tracks (like BLAST) you may want to pull off of master, instead of 2.0.4, but otherwise this should work fine.

**Comment by mictadlo** [comment]
Thank you it works.
