### ISSUE TITLE
One view mode, with controls to show/hide the native track selector and annotator panel views

### ISSUE THREAD

**Issue by childers** [GMOD/Apollo#1332]
From a discussion with @nathandunn:
We had talked about whether we could just log straight into the annotator panel view, or offer some easier to find toggles for enabling/disabling the native track selector and the annotator panel. 

Personally I would love it if there was just one mode and a preset preference to the 'JBrowsey' view (server set defaults and cookies to save user preferences?). Instead of the Show annotator panel and Full Screen buttons, some larger toggles in the upper left and right to open the track selector and annotator panel, respectively. 

I realize this eats into the horizontal real estate, so even more care needs to be taken for keeping a responsive design, but that might be easier than continuing to support two separate views that seem to behave differently in some situations.

I made a quick mockup to illustrate what I was thinking about.

![mockup-selector-toggles](https://cloud.githubusercontent.com/assets/421248/20156853/251966fe-a6a0-11e6-8567-eae883fdaae7.png)

**Comment by nathandunn** [comment]
Perfect.  Thanks

**Comment by nathandunn** [comment]
http://stackoverflow.com/questions/36256007/how-to-hide-panel-with-animation-css-sliding-effects-in-gwt

**Comment by nathandunn** [comment]
- [x] add URL option for showing native track label
- [ ] add URL option for setting annotator panel on / off
- [ ] add a sliding panel control the native track selector (at the top)
- [ ] add a sliding panel control for the annotator panel?
- [ ] remove full-screen view option (except when logged out as JBrowse)
   - [ ] login should redirect
   - [ ] ??

**Comment by nathandunn** [comment]
Backup for sliding panel is just to replace the "full-screen-view" with "show native track selector" or something like that.

**Comment by erasche** [comment]
:+1: for this! Would love it as well. Basically nonr of our users can use admin / any of the apollo panel features, so going straight to jbrowse track selector and hidden apollo menu would be optimal. We'd even considered moving admin management of orgs and those features into a separate webapp

**Comment by nathandunn** [comment]
@erasche  Is this because you have a limited number of scaffolds / annotations?

**Comment by erasche** [comment]
- hierarchical track organisation in JB
- annotations < 500

Wish we better able to make use of the apollo UI components.

**Comment by nathandunn** [comment]
@erasche  No worries.    My hope is that we can either implement our own hierarchical track selector (really wouldn't be that hard), or we can move the div into the track panel once @enuggetry  has some time.    

In the interim (and while I work on getting this fixes), you can either have user's click on "Show Browse Track Panel" in the Track Tab or pass in ```&tracklist=true``` into the url string.  I should fix it so that it also takes '1' as well (which would be pretty easy).    

I would still think that it would be pretty helpful to have the Annotations Tab with anything more than 20 genes, but I'm unfamiliar with the workflow.    Either way, it would be good / not hard to make it configurable.  I'll try to have something by next week.

**Comment by nathandunn** [comment]
Also @erasche  if you close it once by clicking on the icon, it will remember that you closed it within the same browser.  The use-case I think that both you and @childers  have is what happens if you come in from a separate application (which is reasonable). 

<img width="876" alt="screen shot 2016-11-10 at 3 33 57 pm" src="https://cloud.githubusercontent.com/assets/751274/20198736/2316014e-a75b-11e6-861d-af9eaf4fca3e.png">

**Comment by nathandunn** [comment]
Worth having some feedback from @monicacecilia  and @deepakunni3  when we have a moment.

**Comment by nathandunn** [comment]
An example of a snackbar (a widget that pops up at the edges of the screen).  Would have to be activated if a panel disappears.

**Comment by childers** [comment]
@nathandunn Thanks for confirming that the state is persistent based on how the client opens/closes the annotator panel.  

The other part of this was whether this can be set by default, either through the URL, as in the case of the tracklist ```&tracklist=true``` or in some admin or server default setting.

**Comment by nathandunn** [comment]
When the PR #1332 comes in, you will be able to do:

&tracklist=true&openAnnotatorPanel=0

It does occur to me that if I implemented the heirarchical box it would get rid of this requirement as well as simplify editing of the configuration. .

**Comment by nathandunn** [comment]
Closed this with a PR before @monicacecilia  had a chance to comment.  We had discusses this today.   I think our feeling was that between being able to use the URL to monitor the initial view as described above and being able to use the [open-close on the i-frame next to the link button](https://github.com/GMOD/Apollo/issues/1332#issuecomment-259839793) or dragging the box should feel pretty natural to most users.   This had not been an issue when training users. 

In #1337 I changed the open-close box to use chevrons, similar to galaxy

Additionally, when clicking on annotation, it shows detail, but doesn't navigate until you click on the ['navigate to here' button](https://github.com/GMOD/Apollo/pull/1337#issuecomment-260511425).  

User's wishing to show/hide the track selector [can do so on the track panel](
<img width="672" alt="screen shot 2016-11-14 at 2 46 07 pm" src="https://cloud.githubusercontent.com/assets/751274/20288782/b3a2e2fe-aa8a-11e6-8b7d-128f1f3f07e7.png").  

Per #1335 . . we plan to add hierarchical track selection to the RHS at some time, by parsing the trackList.json object.  If anyone wants to get started on that, I'd be happy to help.

**Comment by monicacecilia** [comment]
It is already currently possible to: 
- hide/show the Apollo _'Annotator panel'_ with one click, using the arrow at the top of the divider (see number 1 in figure below).
- hide/show the JBrowse _'Track' selection panel'_ with up to two clicks (see number 2 in figure below): one click to reveal 'Tracks', one click on box to toggle the JBrowse native selection panel. This panel can be configured to be displayed in the default setting for JBrowse, in hierarchical form (as requested above), and in faceted form.

These options are available without navigating away from the default Apollo window, thus without using the _'Full-screen view'_ / _'Annotator Pannel'_ options. And users may be currently pointed to this functionality in order to display the browser + annotation window. 

![display-full-screen-toggle_2016-11-15](https://cloud.githubusercontent.com/assets/1714621/20314890/bb3504f8-ab10-11e6-979d-454c6fef0095.png)

Given that the requested functionality is already available, I am scratching off the added features @nathandunn listed on Nov-10.

We will work on: 
- [ ] making available the option to set up Apollo so that users view the _'Full screen view'_ of the browser window, without the Apollo _'Annotator panel'_ and without a JBrowse _'Track' selection panel'_ enabling the use of this option: <code> &tracklist=true&openAnnotatorPanel=0 </code>
