### ISSUE TITLE
./apollo test fails (release  2.0.5)

### ISSUE THREAD

**Issue by cghiban** [GMOD/Apollo#1409]
It ends with this message:

> | Compiling 317 source files.....
> | Error Error executing script TestApp: org.codehaus.groovy.grails.compiler.PackagingException: Error occurred processing message bundles: Error starting Sun's native2ascii:  (Use --stacktrace to see the full trace)

$ sdk current
Using:
  gradle: 3.3
  groovy: 2.4.7

$ java -version
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b15, mixed mode)

This is happening on a CentOS 6 server and on a Fedora 24 workstation.

The same happens when trying run-local and deploy

Thanks,
Cornel

**Comment by nathandunn** [comment]
The most common reason for this is that JAVA_HOME is undefined or points to the JRE instead of the JDK. 

The gradlew and grailsw try to guess if its not configured and its probably different on your system (we typically test on ubuntu). 

http://genomearchitect.readthedocs.io/en/stable/Setup.html?highlight=JAVA_HOME#production-pre-requisites <http://genomearchitect.readthedocs.io/en/stable/Setup.html?highlight=JAVA_HOME#production-pre-requisites>

Should look something like this:

export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/  # or set in .bashrc / .project
Nathan

**Comment by nathandunn** [comment]
Going to close, but please re-open if setting the JAVA_HOME doesn't work.

**Comment by cghiban** [comment]
I was/am actually running it like this:

> JAVA_HOME=/usr/java/jdk1.8.0_112/jre/ ./apollo test
and, as I wrote above, it fails.

Not setting JAVA_HOME stops the build earlier.

(I'm not sure how to re-open this issue)

**Comment by nathandunn** [comment]
@cghiban  Two things:

1 - JAVA_HOME should probably be:

    export JAVA_HOME=/usr/java/jdk1.8.0_112/

2 - I would define it in your ```.bashrc``` or ```.profile``` so that it gets picked up in your environment.   A lot of these scripts will fire off their own shell, so its good to have it there.

**Comment by nathandunn** [comment]
Mine looks like this:

```
$echo $JAVA_HOME
/usr/lib/jvm/java-8-openjdk-amd64
$ ls /usr/lib/jvm/java-1.8.0-openjdk-amd64/
ASSEMBLY_EXCEPTION  bin   include  lib  src.zip
THIRD_PARTY_README  docs  jre      man
```

**Comment by cghiban** [comment]
Thank you, this solved it :)
