### ISSUE TITLE
Logging out in one browser should NOT log out user from all browsers.

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#1457]
Working on 2 browsers. 
Logging out of browser 1 should not log me out of browser 2.

**Comment by nathandunn** [comment]
Logging out of all browsers when logging out of one is the correct behavior.   We are a bit aggressive in that we actively notify the user that their sessions (s) have been invalidated as opposed to doing it in the background (so that they don't try to do anything in the meantime).   We actually do several things to make it work this way.

If a user wants to close a window that is fine as well.   They aren't logged out.    

If you have another use-case for this, let me know.  In the interim I'm closing it.
