### ISSUE TITLE
Feature not draggable?

### ISSUE THREAD

**Issue by abretaud** [GMOD/Apollo#1483]
Hi,
Just a quick question: I have deployed 3 genomes with galaxy and dockerized apollo 2 (\o/), and I'm not totally sure it's configured as it should.
Here's what I get with an example gene:
![apollo](https://cloud.githubusercontent.com/assets/238755/22740059/9a233ef6-ee0e-11e6-9dcc-933659b18eba.png)

- does it look as it should ?
- is it expected that the genes are no longer draggable in apollo 2?

**Comment by nathandunn** [comment]
@abretaud  This brings up a few good points:

- by default, if you are using @erasche 's JBrowse plugins, it creates a canvas track (what you have here), which is not draggable.  These tend to have a more optimal rendering (if you are displaying hundreds of features at once), but are not draggable.      What I would like (hint, hint) is to specify the track type when loading the data.   Either way, you can make a copy of the trackList.json entry and change the type from "CanvasFeatures" to          "type" : "FeatureTrack", which will default to HTMLFeatures.   Hopefully this can be automated on import.  From BAM tracks its VERY nice to have both because of the density of features rendered.  

- you should be using this release, downloaded from here: https://github.com/GMOD/Apollo/releases/tag/2.0.6  I had advanced the tag.   I think I remember that the script installs from denovo, so you should be fine.   Should roughly correspond to this (https://github.com/GMOD/docker-apollo).

- by default we ended up removing NeatFeatures in the trackList as even though it worked in many cases and it looks a lot better, we saw some weirdness.  To modify either way, you just adjust the apollo-config.groovy by commenting out [these lines](https://github.com/GMOD/docker-apollo/blob/master/apollo-config.groovy#L108-L113).   You'll have to comment it out and redeploy to see the change.

- I have no idea what is going on with this.  I tested this with some of these similar type features (multiple exons) and did not nee this.  That is very odd.

**Comment by erasche** [comment]
> by default, if you are using @erasche 's JBrowse plugins, it creates a canvas track

The dockerized apollo makes no specifications, that's all in the JBrowse side. Assuming @abretaud is using JBrowse-in-Galaxy, changing track type is already an option! :)

![utvalg_142](https://cloud.githubusercontent.com/assets/458683/22748030/aa411f12-ee20-11e6-9e5d-f9e28158c754.png)

(We could automate on import, but I generally assume that the user was requesting it for a reason, allow them to specify. Maybe we make a note in JiG that HTML features are draggable if going to Apollo. The JiG tool is still mostly focused on JBrowse deployments than on Apollo since we still don't have the features in Galaxy to really push the apollo integration widely.)

**Comment by nathandunn** [comment]
That's great @erasche.  Didn't realize that had been added yet.

**Comment by monicacecilia** [comment]
@abretaud please also note this [note on JBrowse plugins](https://github.com/GMOD/Apollo/blob/master/docs/Configure.md#jbrowse-plugins) in the Apollo documentation.

**Comment by abretaud** [comment]
Thank you all!
No problem, I'll switch to HTMLFeatures, I just naively used the default option.
I use JiG indeed, and I agree we'd better not make the change magically, but maybe an option in Create/update apollo organism? Not urgent for me anyway.
Doing some tests right now, I think I'll need to change JiG to allow specifying `--type mRNA` as I think it's mandatory to display exon blocks (I have gff with gene>mrna>cds/exons).
I also disabled NeatFeatures in my docker-apollo branch (which I updated to 2.0.6 too)

**Comment by nathandunn** [comment]
Re-open if need to.

**Comment by nathandunn** [comment]
Apologize, I didn't notice that you were still testing (and have opened some other issues).   Re-opening.

**Comment by abretaud** [comment]
It's ok for this issue, I changed the track type + disable neatfeature, thanks
