### ISSUE TITLE
Remote User password overwriting

### ISSUE THREAD

**Issue by erasche** [GMOD/Apollo#1485]
My colleague (@elenimijalis) and I are experiencing an issue whereby the user's password gets overwritten.

- We have an admin account that never has remote_user based access, the password continues working.
- We have remote-user based accounts that we also use with our python command line tools. However as soon as we access the web interface (with remote_user), our password gets overwritten in the DB and we have to reset it in order to use the API again.

I'm not quite sure how to patch this, I'm still struggling with groovy quite a bit.

https://github.com/GMOD/Apollo/blob/master/grails-app/services/org/bbop/apollo/authenticator/RemoteUserAuthenticatorService.groovy

I think the log.warns on L41+ should probably be log.info

Here are the logs

- we *do* have a user, we don't see `log.warn "User does not exist so creating new user."`
- by logs, we aren't hitting the authexception (https://github.com/GMOD/Apollo/blob/master/grails-app/services/org/bbop/apollo/authenticator/RemoteUserAuthenticatorService.groovy#L85)

```
2/9/2017 6:06:06 PM2017-02-09 18:06:06,655 [http-apr-8080-exec-7] WARN  authenticator.RemoteUserAuthenticatorService  - Remote user found [esr@tamu.edu]
2/9/2017 6:06:06 PM2017-02-09 18:06:06,657 [http-apr-8080-exec-7] WARN  authenticator.RemoteUserAuthenticatorService  - User exists org.bbop.apollo.User : 1976 ?
2/9/2017 6:06:06 PM2017-02-09 18:06:06,657 [http-apr-8080-exec-7] WARN  authenticator.RemoteUserAuthenticatorService  - for username: esr@tamu.edu
2/9/2017 6:06:06 PM2017-02-09 18:06:06,663 [http-apr-8080-exec-7] WARN  apollo.PreferenceService  - Multiple preferences found: 40
```

I'm not sure where password could be getting overwritten. Any ideas?

**Comment by nathandunn** [comment]
My understanding is that if REMOTE_USER is defined, then that user is authenticated.   If REMOTE_USER is not defined then we can't use this authentication mechanism and we should go onto the next authentication mechanism.

[This behavior is probably not want you want then](https://github.com/GMOD/Apollo/blob/master/grails-app/services/org/bbop/apollo/authenticator/RemoteUserAuthenticatorService.groovy#L85-L102) says that IF you have a remote_user defined (which you do), but the password given is incorrect (which it will be), go ahead and log them in anyway with a new password, since we always trust the remote_user.  I store the temporary / garbage / hashed password in the metadata and login with the metadata next time since REMOTE_USER is always correct.  I probably shouldn't be defining this as a non-JSON string though (please feel free to change, should really be a JSON string!).  

You can try and get rid of [this section](https://github.com/GMOD/Apollo/blob/master/grails-app/services/org/bbop/apollo/authenticator/RemoteUserAuthenticatorService.groovy#L89-L100) and just return false, but I don't think that is what you want to do.   

If you can't change the authentication header at the top-level (i.e., not setting the header for some users in Galaxy) then you could possibly add exceptions in the user metadata e.g. ```{ allow_remote_user: false }``` or the configuration metadata  similar to what @abretaud for default_group e.g., ```{ exclude_users: ["superadmin","bob@demo.com"] }```, etc.

> I think the log.warns on L41+ should probably be log.info

Agreed.

**Comment by erasche** [comment]
> REMOTE_USER is defined, then that user is authenticated. If REMOTE_USER is not defined then we can't use this authentication mechanism and we should go onto the next authentication mechanism.

yes, absolutely. That's exactly what we want. If this was not the case, it would make other forms of access (programatic access would be tougher since apache/nginx strip remote_user headers (as they should, otherwise you could impersonate anyone)).

>  This behavior is probably not want you want then says that IF you have a remote_user defined (which you do), but the password given is incorrect (which it will be...

I'm not sure we're hitting that route, we don't see the log.error messages at all. As far as I can tell, we don't enter `if (!user), we just hit

```
authToken.password = user.metadata
subject.login(authToken)
return true
```

>  I store the temporary / garbage / hashed password in the metadata and login with the metadata next time since REMOTE_USER is always correct. 

So this means every session the user opens updates their password to a new random value? Since I know nothing about shiro / auth in groovy/grails, is there any way to just declare "This is the user/session" without resetting or validating their password?

> You can try and get rid of this section and just return false, but I don't think that is what you want to do.

Agreed, I don't think so either, not seeing any of those logging messages so I don't believe changing that would affect us.

> If you can't change the authentication header at the top-level (i.e., not setting the header for some users in Galaxy)

miscommunication on my end, that wouldn't solve the issue. We want all of our galaxy users working as remote_users, but some of them also want API access. If there's no easy auth side solution, I can add "bot" accounts for people to use. With remote_user, there will be no way for someone to accidentally get logged in via the remote_user auth method and to have their password overwritten, so the bot account would be safe from this.

**Comment by nathandunn** [comment]
So, I **think** the solution then might be to simply [log a warning and return false here] (no password settings) (https://github.com/GMOD/Apollo/blob/master/grails-app/services/org/bbop/apollo/authenticator/RemoteUserAuthenticatorService.groovy#L86-L102) so that it then uses the next authentication scheme. 

If you create an admin user before you create the registered user they should just fail the REMOTE_USER authentication each time and then move onto the username/password authentication strategy.  

I have it setup this way as one day we may want to use other OAuth strategies and and potentially not use username / password at all.

**Comment by nathandunn** [comment]
Please re-open if still a problem
