### ISSUE TITLE
Slight vulnerability: a user can use the API to create arbitrary filesystem paths

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#152]
https://trello.com/c/VvyBCiwn

**Comment by selewis** [comment]
That sounds nasty. Any way of closing it?

**Comment by cmdcolin** [comment]
I tested it again to confirm that it is still a problem in 1.x. Refer to the trello card for the command. I can also start looking into a fix

**Comment by cmdcolin** [comment]
I think I fixed the bug so now it will only open the session data and create database files if the user is authenticated. This prevents nonsense files from being created.

If we want, we can add an extra layer to prevent directory traversals too, but since the allowed track names are currently loaded in the database, it is not possible to do the directory traversals anymore.

**Comment by nathandunn** [comment]
I will test.

**Comment by nathandunn** [comment]
reviewed and looks correct.  Session only opened when needed and user is authenticated.
