### ISSUE TITLE
unable to determine MIME type

### ISSUE THREAD

**Issue by childers** [GMOD/Apollo#166]
I've started getting this error a lot since updating to 1.0.4-SNAPSHOT. 
``` bash
08:21:15.605 [http-bio-8080-exec-4] ERROR  - Could not get MIME type of /path/to/data/bigwig/Ofas.scaffolds-GAPS.bigwig falling back to text/plain
08:21:15.733 [http-bio-8080-exec-6] ERROR  - Could not get MIME type of /path/to/data/bigwig/Ofas.scaffolds-GAPS.bigwig falling back to text/plain
08:21:15.769 [http-bio-8080-exec-3] ERROR  - Could not get MIME type of /path/to/data/bigwig/Ofas.scaffolds-GAPS.bigwig falling back to text/plain
```

**Comment by cmdcolin** [comment]
Currently we have some hardcoded assumptions that makes it require .bw filetypes for the JBrowseDataServlet


In this case, it doesn't matter since it is expecting text/plain anyways for bigwig files, but if you renamed them to .bw it would reduce the errors

This could be something that could be made more configurable though

See https://github.com/GMOD/Apollo/blob/a1e7d9eab9c8dd6c0de4624764f61dcf2c494d3e/src/main/java/org/bbop/apollo/JBrowseDataServlet.java#L89

**Comment by childers** [comment]
Thanks for the clarification!

**Comment by childers** [comment]
I'd like to request adding .bigwig to that block of tests if possible.

**Comment by nathandunn** [comment]
@deepakunni3   This can be closed, right?

**Comment by deepakunni3** [comment]
@nathandunn Yes. It has been tested and it works for *.bigwig files.
