### ISSUE TITLE
Enable Chado export from Annotator panel

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#1685]
I know this is in the works, but there is no longer an issue discussing it. Bringing it back to the table.

**Comment by monicacecilia** [comment]
This issue used to mention 'Chado', but it was removed. https://github.com/GMOD/Apollo/issues/1121

**Comment by nathandunn** [comment]
Just removing all milestones that are not 2.0.7  or 2.1.0.  

Just to clarify, would the idea be to be able to push individual genomic elements to Chado instead of all at once on the Sequence Panel?  

Was this for inserting / updating / deleting individual Tripal elements (which would be an awesome use-case)?   

Hopefully we can keep the same uniquename, as well.

**Comment by nathandunn** [comment]
The importance of the uniquename is that we need to lookup an existing chado implementation.  Also unsure if we want to facilitate the ability to pull them in from Chado as well and how many annotations we would be looking at.

**Comment by nathandunn** [comment]
this is reality
