### ISSUE TITLE
The "Previous" button on the sequences page doesn't update datagrid

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#176]
Found while testing 1.0.4-RC3

![screenshot-localhost 8080 2015-02-23 15-55-20](https://cloud.githubusercontent.com/assets/6511937/6338430/7456de5e-bb74-11e4-818f-c4507faf0a34.png)

**Comment by monicacecilia** [comment]
darn! good catch, thanks! 
it did on RC2, right?

**Comment by nathandunn** [comment]
Confirmed about RC2.  I’ll fix it in the mainline.  

Nathan

**Comment by cmdcolin** [comment]
It's already fixed here https://github.com/GMOD/Apollo/commit/39b9fd4ec34f61d542784e0a4796063acbe8e550

**Comment by nathandunn** [comment]
Great thanks.    If this is the only thing (knock on wood) I’ll tag without the RC4.  

Nathan

**Comment by cmdcolin** [comment]
It looks like the search button is weird too. Doesn't match full strings.

![screenshot-localhost 8080 2015-02-23 16-12-54](https://cloud.githubusercontent.com/assets/6511937/6338771/e54a8fdc-bb76-11e4-9115-cc2016c4669f.png)
![screenshot-localhost 8080 2015-02-23 16-12-27](https://cloud.githubusercontent.com/assets/6511937/6338772/e9200970-bb76-11e4-9302-72217e0994b8.png)

**Comment by cmdcolin** [comment]
Oh, actually, the problem is when you have the "Offset" specified AND you search for the string. I think the search should reset the offset to 0

**Comment by nathandunn** [comment]
@monicacecilia   Whatever you think is the most intuitive.  I think I played with it both ways, but doesn't mean I ended up with the correct solution.

**Comment by cmdcolin** [comment]
I guess I'll leave it as is. The workaround would be sort of non-intuitive due to the current way things work.

**Comment by monicacecilia** [comment]
@nathandunn As I understand the current design, the two searches cannot be combined. That is, either the curator is looking for a known (or partially known) sequence (group/scaffold/chromosome) and enters the ID (or partial ID) on the "Search by Name" field, or the curator browses through all sequences, visualizing a finite number of sequences at a time. The curator can also determine where the display of sequences begin -- that is, s/he can offset the 

1. In my ideal WA UI, a curator is able to:
1.1- enter the name or fragment of a name of the sequence, and browse through the results (functionality already there)
1.2- use the "previous" and "next" buttons to browse through the pages (functionality already there)
1.3- limit the number of results displayed at a time with a drop-down menu (functionality already there)
1.4- sort the entire list of sequences (and results) by  "Name" or "Length" (functionality not there, _repeatedly requested through the annals of time_).  

2. Also in my ideal UI, there is not:
2.1- an "offset" box for the "previous" and "next" results, because frankly, its use is quite confusing to me.

IMO 1.4 and 2.1 can wait until 2.0, and we can clarify the use of the current search boxes and results on the user guide. So I better get to that.

cheers, 
~moni.

**Comment by monicacecilia** [comment]
Oh, since we are looking at the "Sequences" page, the "Help" menu is missing the "Web Apollo Help" menu item. Could we please add it? 

![screen shot 2015-02-23 at 3 45 53 pm](https://cloud.githubusercontent.com/assets/1714621/6340335/38e16444-bb73-11e4-92e4-bfbcf0b01731.png)

**Comment by nathandunn** [comment]
You sure you want it on this page?   I didn’t add it here as it doesn’t apply to anything on this page.  

Nathan

**Comment by nathandunn** [comment]
1.4 you won’t be able to do with this interface.  You can do this with Colin’s older interface as long as you don’t have too much data.  

This is because a back-end sort would require a full scan of the database which causes a memory leak, ergo 2.0.  


Yeah, I’m itching to get this out as well.  


Nathan

**Comment by monicacecilia** [comment]
Yep, as I said, 1.4 & 2.1 can wait for v2.0

Yes I am sure.

~m.

**Comment by monicacecilia** [comment]
Fixed. Thank you!
