### ISSUE TITLE
support indexed FASTA genome for reference sequence

### ISSUE THREAD

**Issue by deepakunni3** [GMOD/Apollo#1778]
Apollo should start supporting FAI indexed genome. Currently this is supported by JBrowse without any modifications needed. 

This would make the whole process of setting up Apollo quick and easy.
And it would be very helpful moving forward with adding new features to Apollo.

**Comment by nathandunn** [comment]
- [ ] support FAI within refseq
- [ ] change genome methods to use fasta index method by default if available (https://github.com/samtools/htsjdk/blob/master/src/main/java/htsjdk/samtools/reference/FastaSequenceIndexCreator.java)

**Comment by Yating-L** [comment]
@nathandunn I saw multiple open issues/pull on supporting FAI index and GFF3 Tabix tracks. I am wondering are they still in progress? I would like to have an idea of where are they now. Because I am about to refactor the tool to produce gff tabix files instead of millions of json flat files.  Thank you!

**Comment by nathandunn** [comment]
@Yating-L   I should start to pull fixes over.  

FAI should work already.  
Canvas should work now with histograms

I need to work on the HTMLFeatures / GFF3Tabix code for JBrowse.  There are some minor fixes that need to be in there and @rbuels  wants https://github.com/GMOD/jbrowse/issues/969 in there for 1.13.0    Hopefully I can get it most of the way by next week.

**Comment by nathandunn** [comment]
@Yating-L  the PR I've started is here (for JBrowse): https://github.com/GMOD/jbrowse/pull/996  

As much as I would like to get this in correctly, but I also have a lot of things.  However, if you wanted to fork and continue this work in your own PR (which would subsume this one), that would be amazing.  Otherwise, it will happen when it happens.

**Comment by Yating-L** [comment]
@nathandunn Thank you for point it out! I'll work on it. Does the GFF3 tabix and FAI support for JBrowse would also work for Apollo or there will be additional work for Apollo later?

**Comment by nathandunn** [comment]
Most things for JBrowse will automatically work for Apollo.  

FAI support for JBrowse works for Apollo (if not, let us know). 

GFF3 Tabix works for JBrowse Canvas (including the gene).  

GFF3 Tabix works for HTMLFeatures but ONLY if you remove the gene line from the GFF3 (this was the bug I was working on).  


I think the annotation fix for Apollo should be in there (if you create an Annotation object from a GFF3Tabix track), but I’m unsure.  If not, it was a pretty easy fix. 

Nathan

**Comment by Yating-L** [comment]
@nathandunn FAI works for JBrowse but not Apollo, I cannot load the organism if it is FAI.

GFF3 Tabix does not work for HTMLFeatures with nested features (gene-mRNA or transcript-mRNA), only show part of the subfeatures in JBrowse. I am not able to test this for Apollo yet.

**Comment by nathandunn** [comment]
I know that GFF Tabix does not work for HTMLFeatures.  I thought I would have more time to work on it.  

For FAI / FASTA, this should work (right @deepakunni3 ?!).    What config are you using for it?

**Comment by nathandunn** [comment]
This should be fixed by #1791, but re-open if I misinterpreted it.
