### ISSUE TITLE
Bug with CDS for NM_019083.2

### ISSUE THREAD

**Issue by Wozzerv** [GMOD/Apollo#1813]
I was just testing some of my new features on my build on the LAMP server I am working on and I found something strange with this transcript within the GenBank TopLevel- Canvas track at position chr1:100133043..100133419 (378 b).

Essentially I know that the CDS for this transcript starts at base 20. This is supported by the graphic for this transcript on the appropriate track. 

However when I place this transcript into the User-Created Annotation Track it believes the CDS starts at base 2 at a G. Not the A of the ATG at base 20. I cant test this on your community build as I dont have login details but I assume it will perform the same operation?

Just wanted to bring this up. Let me know if you need me to provide any details from my Build.

**Comment by deepakunni3** [comment]
@Wozzerv When an annotation is promoted to the User-Created Annotation Track, Apollo calculates the longest possible ORF for that annotation. In the case of NM_019083.2, this behavior is visible by the change in CDS start from 100133169 to 100133151.

There are two ways to override this behavior:
1. In your `apollo-config.groovy` where you specify `use_cds_for_new_transcripts = true`. You can see this configuration in https://github.com/GMOD/Apollo/blob/master/grails-app/conf/Config.groovy#L201
2. Do a 'Set Translation Start' operation after adding the annotation to the User-Created Annotation track.

**Comment by deepakunni3** [comment]
This is not technically an issue since its the desired behavior. But feel free to reopen this issue.

**Comment by Wozzerv** [comment]
Can I ask what is desired about this behaviour? It seems strange to move the CDS from the actual location to not even to a start codon.

**Comment by nathandunn** [comment]
<img width="348" alt="screen shot 2017-11-17 at 8 22 33 am" src="https://user-images.githubusercontent.com/751274/32957422-8091dc8c-cb70-11e7-86eb-0a301af6d077.png">

**Comment by nathandunn** [comment]
The "issue" is this:

https://github.com/GMOD/Apollo/blob/master/grails-app/services/org/bbop/apollo/FeatureService.groovy#L1114-L1126

from

https://github.com/GMOD/Apollo/pull/1307

and 

https://github.com/GMOD/Apollo/pull/1302

Still trying to get my head around if this is correctly solving for the use-case correctly.  

Its definitely a longer translated protein (our goal), but am unsure if this is the edge-case we are trying to fix.

**Comment by deepakunni3** [comment]
@Wozzerv Its the desired/default behavior because the change in the CDS can sometimes hint annotators to consider the fact that there might be a functional exon upstream that was missed by automated gene prediction pipelines. This becomes more obvious when you look at existing gene prediction tracks along with RNA-seq BAM tracks. Since manual curation of annotation aims at refining the pitfalls of automated gene prediction, such hints tend to aid in the process of annotation. The change made by Apollo to the CDS is only a *hint*, and thus we provide additional options like 'Set Translation Start' and 'Set Translation End' which gives control to the annotator in determining the boundaries of a transcript's CDS.
