### ISSUE TITLE
allow custom date formatting for GFF3 files

### ISSUE THREAD

**Issue by mpoelchau** [GMOD/Apollo#184]
A minor quibble, but I thought I'd bring it up - the month numbering in the gff3 export starts with 0 instead of 1, so if you're expecting to see a February creation and modification date, you'll see what looks like a January date, instead. I've seen this in 1.0.4-RC3 and the November 2013 versions of Web Apollo.

**Comment by nathandunn** [comment]
@mpoelchau  @monicacecilia  Just to clarify.  It has stayed the same between versions? 

We have to be a bit careful about this, as its done both for human and machine readability.  

My thought would be to have (yet another) configuration for specifying dates throughout the app so that if I decided to output as Jan-07-2015 from server A, it could do an ingest the same way.   Personally, because of the internationalization (MMDDYYYY), I always find it best to write things out like I did above or use a standard GMT/UTC string (Mon, 03 Jul 2006 21:44:38 GMT) or use an ISO string.

Is this something you need for 1.0.X or should we schedule it for 2.0?    We are working on this piece right now.

**Comment by mpoelchau** [comment]
Sorry - I had no idea this would be a big deal! FYI, the day numbering (not month) starts with 1, not 0 - not sure if this makes things more difficult for you. So, an annotation I made today dates to 2015-02-3. 
This is definitely a very minor issue, so certainly 2.0 or even later would be fine. Since I've seen it in both the 1.0.4-RC3 and the November 2013 versions, I assume it's been there the entire time.

**Comment by nathandunn** [comment]
I think its a good idea either way.  Its silly to have something be an artifact of the way Java implements its date function.   Its not consistently human or machine-readable outside of Apollo.

**Comment by nathandunn** [comment]
@spficklin   FYI, not sure how you are parsing the GFF3 dates on import into GenSAS, but wanted you to be aware just in case.

**Comment by spficklin** [comment]
Are you referring to dates in the header comment information of the GFF for when the GFF was created?  Or are these dates associated with annotations?  

We don't currently parse dates in GenSAS.  But I agree that the month would be less confusing if it started with 1 rather than 0.  My personal preference for writing out dates is always YYYY-MM-DD (E.g. 2015-01-02).  It's not standard for humans but it does support sorting of elements by date (not sure that's applicable for GFF files).

**Comment by selewis** [comment]
Nathan,

Couldn't it be DDMMYYYY rather than MMDDYYYY?

Much better for sorting on date easily.

But spelling it all out (Mon, 03 Jul 2006 21:44:38 GMT) or an ISO string is
nicest.

I'd vote for 2.0n if possilble

**Comment by selewis** [comment]
+1  YYYY-MM-DD

**Comment by nathandunn** [comment]
I think that YYYYMMDD or YYYY-MM_DD may make the most sense.  Regardless, it *should* be formattable and whatever goes out should come in.   I have scheduled it for 2.0 and will give it to @deepakunni3  to chew on as he's already working on this code.    Thanks for the input.

**Comment by monicacecilia** [comment]
This has been solved - YYYY-MM-DD was adopted.
