### ISSUE TITLE
Connection to GOLR fails, unable to add GO terms.

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#190]
Unable to add GO terms. 
Error on console: 
<code>
GET http://a2-proxy1.stanford.edu:8080/solr/select?defType=edismax&qt=standard&…e_id%5E1&json.wrf=jQuery17106870290483348072_1425692421690&_=1425692716805 net::ERR_CONNECTION_REFUSED
</code>

Apollo is trying to reach this URL: 
http://a2-proxy1.stanford.edu:8080/solr/select?defType=edismax&qt=standard&indent=on&wt=json&rows=10&start=0&fl=*,score&facet=true&facet.mincount=1&facet.sort=count&json.nl=arrarr&facet.limit=25&fq=document_category:%22ontology_class%22&fq=source:(biological_process%20OR%20molecular_function%20OR%20cellular_component)&facet.field=annotation_class&facet.field=synonym&facet.field=alternate_id&q=GO:&qf=annotation_class%5E5&qf=annotation_class_label_searchable%5E5&qf=synonym_searchable%5E1&qf=alternate_id%5E1&json.wrf=jQuery17106870290483348072_1425692421690&_=1425692716805

Seth mentioned the new, stable, *for ever* URL is:
http://golr.geneontology.org/

Also, some issues with the "Add" option -- but seem to be time-depending. I'm ignoring for now. Alas, RC **CANNOT** go out with wrong call for GOLR.

**Comment by kltm** [comment]
Just to clarify the the URL, the new one should look like:

 http://golr.geneontology.org/solr/

It is currently believed that this is the '''forever''' URL.

**Comment by monicacecilia** [comment]
Thank you @kltm !

**Comment by kltm** [comment]
As an update, I believe that production has flipped the switch on the new setup, and due to their firewall rules, the old URLs may not be functional anymore.
If this is a problem, we may be able to get them to turn the old ones back on again temporarily.
@cmungall I don't think anybody else was using our services in anger yet?

**Comment by monicacecilia** [comment]
Well, it may be the case we have to report on the update and let all developers know of the change in URL, even if they are using the old version. 
I believe you are correct, no one *that we know of* is using them in anger. yet.

**Comment by nathandunn** [comment]
@monicacecilia  @kltm   Thanks.  Yes, it would be good to announce it just in case and where to fix it.

**Comment by nathandunn** [comment]
@monicacecilia   This is ready to go on staging.

**Comment by mpoelchau** [comment]
I'm getting a similar error (not the same since we've been using a proxy due to mixed content issues). So, http://golr.geneontology.org/solr/ is the way to go now? I'll let our annotators know to temporarily stop using the GO field until we've updated.

**Comment by monicacecilia** [comment]
Yes, that's the new one. 

The changes have been quite inconvenient but peeps at Stanford promise this *is the one*!

Here's hoping.

**Comment by nathandunn** [comment]
It is fixed in the master (now) and will be fixed in the 1.0.4 release.  

Do you think its worth  a separate announcement as it will effect *ALL* versions of the installed code.  

Worst-case updating from 1.0.3 to 1.0.4 should be pretty easy and require no configuration changes.

**Comment by kltm** [comment]
I have a rather long winded suggestion that would probably go better in its own ticket, but since I'm not sure how usable you'd find it, I figure I can test it here first as it would partially address the disruption caused here by the GO (sorry). It boils down to a single URL announcements file that apollo periodically consumes to communicate with downstream users and installations.

The idea would be that when apollo starts-up, is reloaded, or after a certain period, it checks a URL (or its backup) for a file, maybe from S3 or BBOP CDN or something. If it finds it, it parses out the sets of announcements that have a simple set of fields like: 

: version range list (0.9-1.0, 2.x)
: date applicability range (date when the notice should appear, can be the future for getting ahead)
: announcement type (warn, notice, etc.)
: announcement html

if a set passes the filters, a dismissible announcement occurs. An installation (or user) could opt-out from the system entirely in configuration.

What this would get you is:

* a channel for general announcements
* a channel to get users to update configurations (this issue)
* a channel to announce outages and problems (this issue)
* a way of collecting passive user analytics

I suggest this because you have a broad range of people with different installation types, versions, and awareness of what is going on with apollo.
You may already have a system like this in place, but I thought I'd fly it since I don't know better :)

**Comment by nathandunn** [comment]
We thought about doing the same thing in the server code with duct-tape and bailing wire.  

However, if you do publish an API for the GOLR server that would allow that, that would be great.   I will use it in Apollo2 for sure and in Apollo1 if we have a chance. 

Thanks,

Nathan

**Comment by monicacecilia** [comment]
@nathandunn, this is working now on Staging. Thanks! 
I've sent you the draft text for a separate announcement. Please proofread and send back at your earliest convenience. Thank youuuuu! I'm closing this issue, as it pertains to 1.0.4.

@nathandunn @kltm, I've created a new issue here https://github.com/GMOD/Apollo/issues/194 for future implementation. Thank you!
