### ISSUE TITLE
jbrowse bin directory not in expected location

### ISSUE THREAD

**Issue by trstickland** [GMOD/Apollo#2017]
I encountered this during my upgrade to apollo 2.2.0 (from 2.1.0) and jbrowse 1.16.1 (from 1.12.5).

JBrowse scripts (e.g. `add-bam-track.pl`) used to be found in the `bin` directory under the install target dir, i.e. we install in /apollo, so scripts were in /apollo/bin

Guddling about, I couldn't find any relevant output in the logs, but there is a /apollo/jbrowse/bin directory with the scripts that I require (so it's an easy workaround with a symlink).

Our build is all scripted, and I can reproduce this starting from a clean Ubuntu (docker) image each time -- bin directory is always there with 2.1.0/1.12.5 and always absent with 2.2.0/1.16.1, all other build/deploy steps being the same.

So it looks like a copy step in the deployment has gone AWOL..?

**Comment by nathandunn** [comment]
@trstickland We only support up to JBrowse 1.15.4 in 2.2.0.    It mostly works for 1.16 (some issues with annotating variants still (https://github.com/GMOD/Apollo/pull/1986)), but let me know if end up with any further errors with 1.16. 

But you are correct about the underlying issue.  It seems to be a recursive call and it only seems to not recurse because of dependency issues.  

Are you able to test the fixes for it here. https://github.com/GMOD/Apollo/pull/2019 that would be great.  If not, I can merge it directly.  It is using a symlink as you suggested, which seems to work better.

**Comment by trstickland** [comment]
I will try PR #2019 soon as possible (out of office just now), thanks.

FYI we're on jbrowse 1.16.1 as it has the fix for issue #1942.
