### ISSUE TITLE
bhofmei-jbplugins with Apollo

### ISSUE THREAD

**Issue by mictadlo** [GMOD/Apollo#2119]
Hi @bhofmei, @cmdcolin and @nathandunn,
Is it possible to get this plugin https://github.com/bhofmei/bhofmei-jbplugins running with Apollo?

Thank you in advance,

Michal

**Comment by nathandunn** [comment]
Probably.  Just follow the example laid out in the sample Apollo config for other plugins and cross your fingers.

If it works with the newer jbrowse it will likely work with Apollo.

Just make sure you do an 

apollo clean-all 

Before deploying.

Nathan

**Comment by mictadlo** [comment]
OK, I will try it tomorrow but I am a little concern about whtat the developer wrote https://github.com/bhofmei/bhofmei-jbplugins#jbrowse-versions .

**Comment by nathandunn** [comment]
Ah, then you may have to fork it to work.

@cmdcolin and @rbuels may be able to provide pointers as they have done a few of these conversions already. 

Nathan

**Comment by nathandunn** [comment]
Closing this, as not really an Apollo bug.

**Comment by bhofmei** [comment]
Depending on which specific plugins you want, they do work with the newer versions of Jbrowse. You’ll likely want to install the desired plugins individually rather than as group under the bhofmei-jbolugins repo so webpack finds the plugins correctly. 

There may be some bugs as underlying data structures, variable names change in newer versions of Jbrowse. In that case, create an issue with the specific plugin. Ive been going through and checking compatibility but if you file an issue I’ll look at it immediately.

I hope that helps!
