### ISSUE TITLE
logout button in jbrowse window broken

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#213]

**Comment by nathandunn** [comment]
from @monicacecilia   

When attempting to Logout: 
"ErrorCtor {message: "Unable to load ../Login?operation=logout status: 500", response: Object, status: 500, responseText: "<!DOCTYPE html>↵<!--[if lt IE 7 ]> <html lang="en"…lay:none;">Loading&hellip;</div>↵</body>↵</html>↵", xhr: XMLHttpRequest…}"

**Comment by monicacecilia** [comment]
New logout button on the Annotator panel works. 
The logout button on the JBrowse window does not.

**Comment by nathandunn** [comment]
I need to redeploy this with a "copy_client.sh" command or via the Apollo binary.

**Comment by monicacecilia** [comment]
Aaaaalmost there. 

Both logout buttons in the "Annotator" view work as expected. 

However, the logout button on the "Full screen view" is still somewhat problematic. In summary, more graceful fails should be in place.  

The details are as follows:
1. I am logged in a session
2. Click on "Full-screen view" in the Apollo portion of the window. As a result I get an additional tab with the Apollo view, without the panel on the right. 
3. Click now on the user name and choose to "Logout" of the session. The results are as follows: 
* First, a JBrowse 500 error window (which I imagine I am getting because I am now "logged out". But this is terribly confusing to anyone -- instead it should read "logged out" or some other obvious thing. 
![screen shot 2015-04-14 at 3 04 46 pm](https://cloud.githubusercontent.com/assets/1714621/7148536/acf5df92-e2b8-11e4-9c2d-378afd6f75d3.png)
* Second, the "Annotator" window with Apollo + panel on the right does not automatically log out. Instead I can still drag features, then the display goes bananas and the tracks are in "pending" mode just "Loading" or throwing 500 errors. This, too should be a more graceful fail with a warning that reads "you have logged out" or something of the like. 
![screen shot 2015-04-14 at 3 11 58 pm](https://cloud.githubusercontent.com/assets/1714621/7148547/bb70875c-e2b8-11e4-898d-8498cb0317d5.png)

**Comment by nathandunn** [comment]
@monicacecilia   This is a separate issue that I've moved to #272.   Its related to a few other issues:  #219, #214, #253.
