### ISSUE TITLE
(3d) add a "read only my annotations" user / group level

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#229]
Related to sandboxing.

**Comment by monicacecilia** [comment]
Related to permissions. 
What is the use case here?

**Comment by cmdcolin** [comment]
This has come up in a number of scenarios, but one example is that the DNA subway people wanted annotations to be private for students rather than shared. The alternative was launching hundreds of instances of apollo which would be really bad IMO

Since @tpeng has actually been posting with us lately about DNA subway on https://github.com/GMOD/Apollo/issues/723 I imagine this is still relevant

**Comment by tpeng** [comment]
it's @tengp :p

**Comment by cmdcolin** [comment]
Lol sorry about that ;P!
