### ISSUE TITLE
provide a means of annotating an attributed gene product on a transcript

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#2312]
![image](https://user-images.githubusercontent.com/751274/68423385-e5a78e00-0156-11ea-80d5-4dbc6c0bffb0.png)

Could use similar key/value attribute data that exists now to make work in this workflow.

**Comment by nathandunn** [comment]
I think that this would be a piece of metadata, but would require the ability to annotate to the transcript directly

**Comment by nathandunn** [comment]
Would need to duplicate the GO panel here for Annotated and Alternate:
- add GeneProductInfo object, similar to GO
- Product I guess would be a lookup
- Alternate would be a fllag
- evidence code and reference would be similar, but simpler
- support would be with  field most likely

**Comment by nathandunn** [comment]
FYI @cmungall

**Comment by cmungall** [comment]
OK, if I understand Artemis curators assign gene product descriptions onto transcripts, with evidence. This is analogous to GO annotation, except the annotated triple is entity-has_description-string vs entity-has_role-GO_term. So it makes sense to reuse components across GO annotation and gene product description annotations.

I don't think you can reuse GPAD here though since GPAD is retricted to attaching ontology terms rather than text

**Comment by nathandunn** [comment]
@cmungall  Agreed . . can't use GPAD here.   It looks like an overloaded GFF3 (again) would be the way to go unless there is another comparable format.   Thanks.
