### ISSUE TITLE
In ref sequence tab labels are needed

### ISSUE THREAD

**Issue by selewis** [GMOD/Apollo#239]
The text field for entering the ref sequence ID should be labeled.
and the number (font is too small as well) should clearly state "number of ref sequences"

**Comment by monicacecilia** [comment]
A label clarifying "Number of reference sequences" is still missing. I imagine @selewis means that one should be added next to this number (see 5644 in the image).  Please let us know if otherwise. 

![screen shot 2015-04-14 at 5 41 15 pm](https://cloud.githubusercontent.com/assets/1714621/7150278/9570c85e-e2cd-11e4-830a-05cf5f93a5b9.png)

**Comment by nathandunn** [comment]
this should be removed entirely with the new deploy (replaced with pagination below)

**Comment by monicacecilia** [comment]
It looks informative and useful. :+1:
