### ISSUE TITLE
Add non-editable field in annotation tab to echo what ref sequence currently is being viewed (or add extra column in table)

### ISSUE THREAD

**Issue by selewis** [GMOD/Apollo#242]
That way it clearly differentiates between current status and the text field for searching for a new ref sequence to view

**Comment by monicacecilia** [comment]
@nathandunn I'm not seeing this non-editable field in the Annotation tab that echoes the "Ref Sequence" currently being viewed.

**Comment by monicacecilia** [comment]
@nathandunn I see that the field "echoes" what is being viewed, but the field can be edited.

@selewis this allows users to change from one Ref Sequence to another. Would you like to have an additional field that cannot be edited? ... perhaps the discussion we had earlier about menus at the very top could satisfy this. 
In that way "Organism" and "Ref Sequence" at the very top would not be editable and provide the curators with orientation about here they are. What do you think?

**Comment by nathandunn** [comment]
should be there now after fixing deploy

**Comment by monicacecilia** [comment]
@nathandunn the field in front of "Ref Sequence(s)" echoes what is on display only when the Ref Sequence is chosen by typing the name in that field. If the display changes by using the drop-down menu or by typing its name on the search box on the Apollo window, the field in front of "Ref Sequence(s)" in the Annotation tab remains with the text that reflects the last Group that was typed in it.

**Comment by nathandunn** [comment]
This is a new issue with #279 . .  closing this one.

**Comment by monicacecilia** [comment]
@nathandunn This is an issue @selewis submitted. Below I am describing my observations upon checking on the details she provided for this request and I am resubmitting a question I posed earlier. 

The request was to "[a]dd (non-editable) field in annotation tab to echo what ref sequence currently is being viewed".
Is this _non-editable field in the annotation tab that echoes what ref sequence is currently being viewed_ available? It is possible it is already there and I simply am not able to find it. Please clarify. I have detailed below what is currently visible from here.

#### Information currently visible:

1. When I first log in in Apollo2, the Apollo window goes to a group. I am not sure how this is determined, it is not always the last group I visited, sometimes it is different. Note that none of the fields in the Annotation tab contain information concerning the ref sequence currently being displayed. All fields are empty.
![screen shot 2015-04-15 at 10 23 52 am](https://cloud.githubusercontent.com/assets/1714621/7165062/d37ca9c4-e359-11e4-8f6a-7333bfbc87d2.png)

2. Still in the Apollo window (on the left, not the panel on the right): I can select a different ref sequence, either using the drop down menu or the search box. Even after choosing one, all the fields in the Annotation tab in the panel on the right remain empty. Thus, there is still no indication of "where" the curator is located on this panel. 
**Drop-down menu**
![screen shot 2015-04-15 at 10 27 27 am](https://cloud.githubusercontent.com/assets/1714621/7165120/528c9a12-e35a-11e4-8ed7-75caf8f3d467.png)
**Search box**
![screen shot 2015-04-15 at 10 27 49 am](https://cloud.githubusercontent.com/assets/1714621/7165123/54853036-e35a-11e4-93e8-84d4fb69f0f5.png)

3. When I type the ref sequence in the box labeled as "Ref Sequence" in the gray area at the top of the panel on the right, Apollo navigates to that ref sequence and only then I am able to see that this field now echoes what the ref sequence is. HOWEVER, this is field **can still be edited** and **it is not located inside the Annotation tab**. The "Ref Sequence(s)" box is still empty in the Annotation tab.
![screen shot 2015-04-15 at 10 30 57 am](https://cloud.githubusercontent.com/assets/1714621/7165192/fc432896-e35a-11e4-91be-3f854a6fab8f.png)

4. After I choose to change the information in the field in front of the words "Ref Sequence(s)" in the Annotation tab, the selected ref sequence is only reflected within this tab. This action does not change what is currently being visualized on the Apollo window. I understand that this is expected behavior. 
![screen shot 2015-04-15 at 10 46 05 am](https://cloud.githubusercontent.com/assets/1714621/7165461/a7ae1dca-e35c-11e4-81da-9f6ee68cb4b6.png)

So, AFAICT the request has not been addressed. @nathandunn please explain it to me if I am simply not seeing that you addressed the original request. 

And I ask a question [again] to @selewis: given what is already available, would you like to have an additional field that cannot be edited inside the Annotation tab? Alternatively, perhaps the discussion we had yesterday about menus at the very top could satisfy this. In that way "Organism" and "Ref Sequence" at the very top would not be editable and provide the curators with orientation about here they are. What do you think?

**Comment by nathandunn** [comment]
I guess the question is whether or not you only want to view annotations for the reference sequence you are on or all/any reference sequences.  

I imagine the latter would be more useful. 

Also keep in mind (forgot which bug) that the ref sequence / organism at the top is going to go away and will only display “Current Organism” 

Nathan

**Comment by monicacecilia** [comment]
@nathandunn commented: "I guess the question is whether or not you only want to view annotations for the reference sequence you are on or all/any reference sequences. I imagine the latter would be more useful."

I agree. The user can navigate to annotations available in other reference sequences while still able to see that the panel on the right has information about what's being displayed on the left.

The current state in which the panel on the right always echoes what's happening on the main "JBrowse" window - and vice versa- is optimal. Great job! it's all synchronized now! :ok_hand: :grin:
