### ISSUE TITLE
duplicate sequence fail to specify organism

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#258]

**Comment by nathandunn** [comment]
@cmdcolin   Found this one.

**Comment by nathandunn** [comment]
Related to #214  . . . might need to many of these prefs to database preferences.

**Comment by nathandunn** [comment]
I need to fix this for all operations . . especially in RHS and AEC where fixTrackHeader is called.

**Comment by nathandunn** [comment]
Replace:  
    String trackName = fixTrackHeader(inputObject.track)
    Sequence sequence = Sequence.findByName(trackName)
    permissionService.checkPermissions(inputObject, sequence.organism, PermissionEnum.WRITE)

with:
    Sequence sequence = permissionService.checkPermissions(inputObject, PermissionEnum.WRITE)

**Comment by nathandunn** [comment]
If you have 2 organisms with identical sequence names, switching between sequences on the same organism will arbitrarily select the sequence.

**Comment by monicacecilia** [comment]
@nathandunn I am trying to test this but I need more clarification. When you say "2 organisms with identical sequence names", do you mean "reference sequence" or are you referring to a feature in the Uc-A?

**Comment by nathandunn** [comment]
@monicacecilia   

This is one I have a reference sequence "Group 1.1"  in Organism Honey1 and the same-named reference sequence "Group1.1" in ANOTHER organism Honey2.    It was arbitrarily just annotating / referencing to one or the other . .  now it is only choosing the current sequence from the current organism.

**Comment by monicacecilia** [comment]
BUT, it is adding a character to the name of the gene. For example, if I create an annotation with GB400015-RA in Group1.33 of Honey1, and then go to create an annotation using a gene model named the same GB400015-RA in the same Group1.33 in Honey2, then the newly created annotation has an additional character "a" appended to the end of the original name. 

Is this intentional? It seems a little hacky to me. Is there another way to help organisms in differentiating these?

This is what the annotations look like in Honey1

![screen shot 2015-05-01 at 3 13 38 pm](https://cloud.githubusercontent.com/assets/1714621/7438180/c4c6ff2a-f014-11e4-8146-6f0252f852ed.png)

And this is what they look like in Honey2
![screen shot 2015-05-01 at 3 13 59 pm](https://cloud.githubusercontent.com/assets/1714621/7438187/cd924998-f014-11e4-8e7c-21cf294f69d6.png)

**Comment by nathandunn** [comment]
@monicacecilia   Ah . . so it should be unique name "per organism"?  i.e. ,I can have identical gene names, so long as they belong to other organisms?

The "a" "b" ., etc. is a way to provide unique gene names.  We want folks to customize this eventually.

**Comment by monicacecilia** [comment]
Yes, unique names per organism. The scenario in which we will be looking at two different organisms with exactly the same gene names is unlikely. In the unlikely case that this were necessary, one would identify the names of the genes in some other way, by adding a prefix, or something similar. At any rate, I can explain this in greater length to you at a later time; for now, yes, unique name per organism. Do not include the a, b, stuff.

**Comment by nathandunn** [comment]
Moved the remaining issue to #339.
