### ISSUE TITLE
Some websocket messages not sent to some clients

### ISSUE THREAD

**Issue by garrettjstevens** [GMOD/Apollo#2611]
I've noticed that some websocket message don't get sent to some clients. For example, an action taken in the annotation track triggers a websocket message for all clients, but the same action taken in the annotation panel only sends the websocket message to some clients. You can use the "websocket_login" branch of https://github.com/garrettjstevens/apollo-websocket-test/ to reproduce this. Also, this is using the "development" branch of Apollo.

- Log in to http://localhost:8080/apollo
- Open network tab in browser dev tools and look at the websocket
- Log in to the apollo-websocket-test-app
- Drag the end of a feature in the annotation track
![image](https://user-images.githubusercontent.com/25592344/116158093-4a3c0d00-a6ab-11eb-94f4-ede0b8edd11d.png)
- See the websocket message both in the Apollo dev tools network tab and the "output" of the websocket test app
- Adjust the length of the feature in the "Coding" tab of the side panel
![image](https://user-images.githubusercontent.com/25592344/116157977-1bbe3200-a6ab-11eb-86ad-ffe36958f7e2.png)
- See the websocket message in the Apollo dev tools network tab, but *not* in the websocket test app

**Comment by nathandunn** [comment]
@garrettjstevens  sorry, it took me awhile to figure out what you are saying. 

Yeah, this is because the Annotator Panel (or any of the GWT code) doesn't use websockets, so I use some other eventing piece and not the other.   Part of why it would be good to replace that with the react code that Peter is working on.
 
I'm going to close this as this is more of a feature to implement in JB2 than anything to fix, but if I interpreted this wrong we can fix try to fix tomorrow.

**Comment by nathandunn** [comment]
@garrettjstevens  can we close this now?

**Comment by garrettjstevens** [comment]
Yes, subscribing to the specific organism and sequence fixed it
