### ISSUE TITLE
we should export username on GFF3 export

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#285]

**Comment by nathandunn** [comment]
11) Possibly a bug?
I can't get the username of the person who creates a structure when I dump GFF.
I have 
                <metadata type="owner" />
                <metadata type="date_creation" />
                <metadata type="date_last_modified" />
uncommented in gff3_config.xml but they don't appear to be output when I dump out a GFF file.

**Comment by nathandunn** [comment]
I'm going to let @monicacecilia   review and when I update the server next.

**Comment by monicacecilia** [comment]
@nathandunn 
Is this a feature that will include the name of the user who made each annotation whenever GFF3 is exported on a per/reference sequence, using the panel on the right? 
Or is this a feature that will include the name of the user who made each annotation only when dumping all annotations in all reference sequences because the admin wants to keep track of that?

**Comment by nathandunn** [comment]
@deepakunni3   Should appear in both, right?  I haven't pushed it to test, yet.

**Comment by monicacecilia** [comment]
@nathandunn @deepakunni3 I guess you guys went with "both". I have a feeling someone down the line will be asking for their user name to be removed from the GFF3, so having the option would be better. Let's not forget to work on this when we reach #287

**Comment by selewis** [comment]
AT some point what we'll want is not (just) their login name, but their
ORCID.

**Comment by nathandunn** [comment]
Would be great if we could have a configurable set in the preferences.  

Nathan
