### ISSUE TITLE
Annotation count lost on Organism tab

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#303]

**Comment by jwlin** [comment]
Actually I have been trying to generate statistics for each organism since WA 1.0, and happy to see that WA 2.0 uses relational databases and there is a page displaying annotation count. After looking at the data tables, I came up with this SQL command to generate annotation count for each organism in my testing Postgres DB.
https://github.com/jwlin/Apollo/blob/master/miscellaneous/annotation_count.sql
if it's incomprehensible, there are more simple SQLs I used to construct the final command
https://github.com/jwlin/Apollo/blob/master/miscellaneous/annotation.sql
It works for my testing Postgres DB, but needs more tests on larger data set, and more elegant implementation is possible.
The grails framework should have its own object-relation mapping to access database, so the pure SQL may not work directly, but WA 2.0 with relational DB backend provides the possibility to show real-time statistics by directly accessing the DB. That's what I am trying to do on our portal website. Just for your reference.

**Comment by nathandunn** [comment]
@jwlin   This is great.  You can definitely use pure SQL with Grails.  It just wraps Hibernate, which just wraps JDBC.  There is just less code with Grails.  For the simpler reports, I would just create separate grails pages and use the GORM / Grails methods for retrieval.

**Comment by nathandunn** [comment]
Test: Annotation count should show up on organism tab.

**Comment by cmdcolin** [comment]
It does show up but it doesn't "live update" i don't think. technically our data is a little bit "denormalized" as it is not calculated on the fly, but rather stored in a field in the organism table.

**Comment by nathandunn** [comment]
Yeah, I was thinking about this.   We would have to update every time we had a nav event.  This use-case was to have them show up at all.   My idea was to just give a general idea.   I wanted to do something for reference sequences, as well, but I put it in a later bug report.

**Comment by monicacecilia** [comment]
As @cmdcolin noted, it does not update in real time. Other than that, it's working well. :dancer:
