### ISSUE TITLE
Long pause when switching organisms

### ISSUE THREAD

**Issue by childers** [GMOD/Apollo#309]
When changing organisms, there is a really long wait while the organism data is being downloaded.  In the example below, this pause (TTFB) is nearly fifteen seconds, and the actual file download is .43 seconds.  Have you noticed this? In our test instance that is up now, two assemblies are ~143k scaffolds, and one is ~10k scaffolds. 

![wa2_pauses_on_org_switch](https://cloud.githubusercontent.com/assets/421248/7328300/4fef43aa-eaa2-11e4-9992-8a5312ec078d.png)

**Comment by nathandunn** [comment]
1 - Brown recluse . . . awesome!
2 - Great to see you using and testing 2.0 in the mainline!
3 - I think that this is because its loading all of the ref seq data at once.  

We’ll need to fix that and then load on demand on the annotation panel and the ref seq panel in both the drop-down and the table. 

We’ll make sure to get that fixed.  Thanks for reporting it. 


Nathan

**Comment by childers** [comment]
Yeah, we're trying to get to grips with the new back-end and interface. @littlebunch is keeping us up to date.  Love the new deployment system!

**Comment by nathandunn** [comment]
@childers   @littlebunch  Should be ready in mainline now.    Let me know if this is not much faster. esp. on the sequence and annotator panels (as well as simply switching between organisms).

**Comment by monicacecilia** [comment]
it's fast "enough" for me. :wink: :dancer:
