### ISSUE TITLE
get rid of annoying websocket error

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#312]
We get this error every time.

"Uncaught SyntaxError: Failed to construct 'WebSocket': The URL 'wstomp/580/4dore5q3/websocket' is invalid."

**Comment by monicacecilia** [comment]
I know. I've reported it a few times. Annoying indeed... :-1:

**Comment by cmdcolin** [comment]
I am surprised that websockets are even working despite this error. The SockJS function appears to expect a full url, not a relative URL

**Comment by nathandunn** [comment]
I *think* that it ends up being cancelled and reloaded properly.   Most likely a grails config or .  You would only know it if you loaded the console.

**Comment by cmdcolin** [comment]
This is sort of interesting actually, because I think the reason that it is working currently is because it is apparently using the XHR/long-polling fallback method of SockJS instead of the websocket method

Currently, we have things in our network traffic such as "xhr_send" which indicates that it is using the typical Ajax XMLHttpRequest for updates.

If you pass a full URL to the SockJS function, then these disappear

**Comment by nathandunn** [comment]
i think you are correct.  This *might* explain some of the other issues, as well.   Dag nabbit.

**Comment by nathandunn** [comment]
@cmdcolin   Thanks for finding this bug.   Still can't believe that.   I guess its a good protocol if its hard to tell its if its broken ;)

**Comment by nathandunn** [comment]
@childers  @mpoelchau  I'm not sure if this will change anything in your deployment.  Depending on how the firewall is setup this may be better, or it might be just the same.

**Comment by nathandunn** [comment]
Dupe of #265.
