### ISSUE TITLE
failing build . . . 

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#316]
dojo src not found . . . 

https://travis-ci.org/GMOD/Apollo/builds/60267478

**Comment by nathandunn** [comment]
@cmdcolin   So after "ant gwtc" I see:
ndunn:Apollo% ls web-app/jbrowse/plugins/WebApollo/js/WebApollo.profile.js 

but without the built plugin.

**Comment by nathandunn** [comment]
@cmdcolin   Okay, close when the build is working again.  

How do we rebuild the cache in travis?

**Comment by cmdcolin** [comment]
This menu allows deleting the existing caches, so that they can be rebuilt

![screenshot-travis-ci org 2015-04-27 14-42-03](https://cloud.githubusercontent.com/assets/6511937/7356101/a96f3200-eceb-11e4-93b6-7514fcd2b8d4.png)

Ideally it shouldn't need too much fiddling  but I just did that so hopefully it'll be fixed

**Comment by nathandunn** [comment]
It was.  Thanks!

Nathan
