### ISSUE TITLE
Use glass-pane some asynchronous commands::alternative to double-click action in organism panel

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#317]
The double-click action is very unintuitive in the web environment. I think that most users won't understand that to change their organism, that they have to double click. I think it should be a button or similar to the TrackPanel

**Comment by cmdcolin** [comment]
Since the drop down selection for organisms i.e. this http://webapollo.readthedocs.org/en/latest/images/3.png

it would seem that we need an easier method for changing the organism.

**Comment by nathandunn** [comment]
@cmdcolin  It would be good to do some UI testing.   I think that there are two issues:
1 - what will folks pick up easily
2 - what will be an optimal way of interacting with the environment long-term

I agree that the double-click is slightly non-intuitive, but kind of a pain when switching org's and refseq's.   
A couple of ideas:
A - implement the older drop-down method
B - add a context menu on the different tables with actions such as "switch organism / refseq"
C - add an "action" column . . . 

Would love to get additional feedback: @selewis  @monicacecilia  @childers   (not sure what Monica's @ symbol is).

**Comment by mpoelchau** [comment]
Can you implement both A and C?

**Comment by nathandunn** [comment]
@mpoelchau  Yes.   

For A, the organism would be a drop-down, but the ref-seq is a type-ahead (just due to the large number).   

I'm a little hesitant to do C, unless we have a few actions as it chews up screen real-estate, but to simply keep D (which I just added), but I'm happy to be dissuaded.

**Comment by mpoelchau** [comment]
I see what you mean about C. However, I find double-clicking the organism non-intuitive, as well (especially if the server you're using is slow to respond...). Perhaps if the organism displayed on the left panel were to be highlighted in a particular way on the right hand panel to clarify which organism is being displayed on left vs. investigated on right.

**Comment by nathandunn** [comment]
Comment from @cmdcolin which I can't really disagree with:  " The double-click action is very unintuitive on the web. I can't remember the last time a website used anything requiring a double-click."

My conundrum right now is how to handle different behaviors:
1 - browse data
2 - switch context (refseq / organism)
3 - select data for an action

My takeaway is:
uno - A "double-click" doesn't make sense, and really shouldn't be offered as a primary behavior at all . . but can't really hurt (maybe).  
dos - A "single-click" makes sense for selecting and browsing data, which is the current model, so there 
tres - I should probably add the drop-down of refSeq and organism back version back in.    I had initially removed it, but I think that might have been due to the fact that synchronization between panels was bad.  

I added #319 to correspond to adding the organism to the JBrowse section. 

I think we should implement "tres" (sorry, running out of symbols) and then see where we're add.

**Comment by nathandunn** [comment]
@mpoelchau  @childers @cmdcolin   I think i have a better version of it now.   I kept the coloring, but the organism and reference sequences are both drop-downs / searches as well as displaying the current organism.

![screen shot 2015-04-30 at 2 25 37 pm](https://cloud.githubusercontent.com/assets/751274/7422826/ca7b2cbe-ef44-11e4-83b3-257e6f455b24.png)

The updated version should be on icebox:

http://icebox.lbl.gov/Apollo2/

you can use nathandunn@lbl.gov as the username and the usual password.

**Comment by mpoelchau** [comment]
In theory, this looks like a good approach (although the drop-down boxes could be a big bigger).

In practice, because there is such a long delay between selecting another organism from the drop-down menu, and it actually loading, it is still hard for the novice user to infer what the function of the drop-down menu is. Perhaps there could be some sort of icon that would show that WA is processing a request (like the spinning wheel on a mac) , so the user knows that their action actually triggered something and they should wait? Possibly disable other interactions with the browser while the new dataset is loading?  (Although it would of course be nicest if the new dataset loaded faster :)).
--
Monica Poelchau, Ph.D.
USDA-ARS
National Agricultural Library
10301 Baltimore Ave, Beltsville, MD 20705
monica.poelchau@ars.usda.gov

**Comment by nathandunn** [comment]
@mpoelchau   
I think we can definitely fix that.   It had come up earlier, but I think its always a good paradigm (we had a lot of other things loading as well).  

I'll just create a loading popup for some of these longer operations.

**Comment by nathandunn** [comment]
@mpoelchau   I added a loading dialog for changing organisms.   Let me know if there are other areas that are a bit slow.   I'll try to improve the styling, etc. later., but for now I think it will do the trick.

@deepakunni3  @cmdcolin    Just wanted to FYI you guys on this.  Eventually we'll want to convert all of the "alert" boxes to something like this, though probably using UIBinder so that we can more easily decorate it.

**Comment by nathandunn** [comment]
@cmdcolin  I think something like that might work well for creating large organisms, as well.

**Comment by mpoelchau** [comment]
The new dialog is definitely helpful!

**Comment by nathandunn** [comment]
Test: Glass-pane is the "Loading Dialog". . .

**Comment by monicacecilia** [comment]
Apollo 2 currently supports the following:
1. Glass-pane shows "Loading" dialog.
2. A single click over the name of the organism in the "Organism" tab, reveals the details in the bottom panel (i.e. name, genus, species, directory, Blat database, and Annotations (number)).
3. Switching between organisms can take place by:
- double-clicking on the name of the organism.
- choosing an organism from the drop down menu atop the "Annotator" panel on the right.

All working as expected. I'm closing this issue.
