### ISSUE TITLE
(2h) unnecessary downloads while scrolling

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#332]
While the JBrowseDataServlet effectively sends the cache headers for the static content, it could be better at caching dynamic content because otherwise there are many repeated requests for content

After just a small amount of browsing, over 3MB of data will be downloaded to the browser, and this will be even worse if there are a large number of user-created annotations (i.e. i have 20kb of annotations = 6 annotations, which are repeatedly downloading while scrolling)

![testing](https://cloud.githubusercontent.com/assets/6511937/7434210/a50080c8-effe-11e4-8131-652ef1b6b157.png)

**Comment by nathandunn** [comment]
So, 4 requests are made each time:
1 - setCurrentSequenceLocation: . . . this one is correct .. just sets this in the Annotator, should occur on any nav event.
2 - findAnnotationsForSequence: this should ONLY be called when an annotation is added, edited, or removed
3 - getSequences:  this should ONLY be called if the organism changes . . . I think its because the RefSequence is being called to do a reload

**Comment by nathandunn** [comment]
@cmdcolin   Can you look at this and close it when you have a chance.   It should only make a single call   returning <200 B's each time the genome is scrolled.

**Comment by cmdcolin** [comment]
much better. only calling the relevant service and returning appropriate data
