### ISSUE TITLE
set translation start followed by set readthrough stop codon ends up creating an incorrect readthrough stop codon

### ISSUE THREAD

**Issue by deepakunni3** [GMOD/Apollo#345]
![image](https://cloud.githubusercontent.com/assets/4530272/7480565/fb8bb736-f32e-11e4-9af2-2c657a6e4012.png)

Gene used in test: GB40828-RA

When a user selects a gene, 'sets translation start' and followed by 'set readthrough stop codon', Apollo creates a stop_codon_read_through of 4 bases instead of 3.

![image](https://cloud.githubusercontent.com/assets/4530272/7480648/a647bc6a-f32f-11e4-887c-59dc74e1d753.png)

Bug observed in Apollo 1.0.4 (http://icebox.lbl.gov/WebApolloDemo) and Apollo 2.0

**Comment by monicacecilia** [comment]
Fixed. 

FWIW: In genes with long UTRs in the 5' end, and in general for short genes , "Set Readthrough Stop Codon" should be preceded by "Set Translation Start"  - so that recalculation does not modify the longest ORF and changes the most appropriate CDS. -- As a personal habit, I always "Set Translation Start" before I "Set Readthrough Stop Codon".
