### ISSUE TITLE
(2h) pyu_tracks if no namestore present?

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#371]
When adding the pyu jbrowse data I get the popup "error reading from the name store".   Because of a 404 on the name store and this error:

    2015-05-13 09:49:04,796 [http-bio-8080-exec-4] WARN  apollo.JbrowseController  - Could not get /opt/apollo/pyu_data/names/0fd.json

If there is no names store . . this is a normal condition, right, and we should allow it without killing loading of tracks, right?

**Comment by cmdcolin** [comment]
That actually is actually abnormal

The names store procedure is like this

In newer jbrowse versions, there is a section in the jbrowse config that says something like this



When you run generate-names.pl, it outputs the hashed files like names/0fd.json for example and also adds a section to the trackList.json with the indication of the hashed data store, e.g.

     "names" : {
      "url" : "names/",
      "type" : "Hash"
     }


If generate-names.pl hasn't been run, then it should not be looking for the hashed files. Caveat: it will check for a legacy names store "just in case" if the hashed one isn't there by checking for the file names/root.json, however, it should not be producing the error popup in this case. 

Conclusion: this is unusual and i'd like to know how your pyu data was loaded. if possible, I would re-run the generate-names script on it, because the generate-names script actually had some pretty serious problems in JBrowse 1.11.0-1.11.5 and was only recently fixed in JBrowse 1.11.6

**Comment by cmdcolin** [comment]
Note: I don't get problems when i do a fresh loading of the pyu_data, with or without running generate-names.pl

example

    bin/prepare-refseqs.pl --fasta ~/Data/pyu_data/scf1117875582023.fa --out /opt/apollo/pyu_data
    bin/flatfile-to-json.pl --trackLabel pyu --gff ~/Data/pyu_data/scf1117875582023.gff --type mRNA --out /opt/apollo/pyu_data/
    client/apollo/bin/add-webapollo-plugin.pl --in /opt/apollo/pyu_data/trackList.json 
    bin/generate-names.pl --out /opt/apollo/pyu_data/

**Comment by nathandunn** [comment]
I’m wondering if its just bad version of pyu_data . . .

**Comment by nathandunn** [comment]
I'm going to chalk it up to old jbrowse data being used with a newer jbrowse.
