### ISSUE TITLE
(2h) Unable to update organism directory

### ISSUE THREAD

**Issue by childers** [GMOD/Apollo#386]
Was the ability to update the Directory removed at some point? I had updated the directory to point to a bad location, and now am unable to change it back. We did a pull in the intervening time, so I was wondering if that was the issue.  I just checked icebox, and am not able to update the Directory field there either. If this is the intended behavior, I can simply update directly. If not, could you at lease allow the Directory to be updated if the check for a trackList.json fails?

**Comment by nathandunn** [comment]
@childers   It should be updateable, just like it was.    That needs to be fixed.

**Comment by nathandunn** [comment]
Looking more closely at the code, you now have to hit "reload" after you change the directory in order to have it reload the data.   Am wondering if this should be done automatically as it was before, but either "halt" the screen, or have the reloading icon (which should probably be marked "reloading") spin and gray out during that process.  

In the interim it will work (though you might have to reload the page).  

I'm also getting a bug on the back end, which is a bug that I need to fix:

    Detail: Key (id)=(325213) is still referenced from table "preference".; nested exception is org.postgresql.util.PSQLException: ERROR: update or delete on table "sequence" violates foreign key constraint "fk_i94ksmdxi88hcqnuycebgkdvs" on table "preference"
    Detail: Key (id)=(325213) is still referenced from table "preference".
    loading the index
    getFeatures for organism -> Honey 3 and NC_012920

**Comment by nathandunn** [comment]
@childers  

If you need a workaround while I get this fixed, you can delete everything from the preference table (or even better, just for that organism. 

In the interim, the more I think about it, the more I think it would be a good discussion.  Also, if you change the reference sequences (and thus reload them) it will likely delete any annotations on this, since the underlying reference sequence they were built on has changed.  

However, if you are simply changing directories and the underlying data is staying the same (i.e., the sequence names and numbers don't change) that should not be a problem (or it should throw up an error if so).   

Once you change the directory, it should change instantly (but won't reload the reference sequences).   I actually think that maybe we should not reload reference sequences at all, since it can only lead to catastrophic failure.   Really, a new organism needs to be created if your assembly changes significantly (data as opposed to formatting, which would be fine).

**Comment by nathandunn** [comment]
@cmdcolin  Would be curious on your thoughts as well on this.

**Comment by nathandunn** [comment]
I am getting this error now:

2015-05-15 11:50:44,961 [http-bio-8080-exec-10] ERROR apollo.OrganismController  - problem saving organism: java.lang.Exception: Invalid directory specified: /data/jbrowse/data-amel-demo2

It also looks like if you ever specify an invalid organism directory via an update, it kind of gets locked in there.

Proposal:
1 - only load reference sequences when creating and otherwise disallow

I think that this will actually fix most cases and is the right behavior.  Thoughts?

**Comment by childers** [comment]
I agree with you that changing the underlying assembly will break all existing annotations, so there should be a distinction between updating the assembly and updating the location to the same assembly.

I think your suggestion is fine, as long as the understanding is that if you mess up at creation time you have to start over from the beginning. I ran into this issue because of an accidental change, and it locks up because it is no longer pointing to a valid data directory resulting in me being unable to correct my minor typo.  If it was locked down from the start, this would have all been avoided.

If I mess up and add the wrong data directory at creation and catch it later, I don't think it is too unreasonable to force a wipe and reset. My thought is that it might be frustrating, but it is much less problematic than the possibility of keeping annotations made for a different reference.

**Comment by cmdcolin** [comment]
The problem was that checkOrganism (which should be called something like checkDataDirectory) was trying to validate the old directory instead of validating the new data directory that the user inputted

Proposal
    diff --git a/grails-app/controllers/org/bbop/apollo/OrganismController.groovy b/grails-app/controllers/org/bbop/apollo/OrganismController.groovy
    index a58c1c1..022d076 100644
    --- a/grails-app/controllers/org/bbop/apollo/OrganismController.groovy
    +++ b/grails-app/controllers/org/bbop/apollo/OrganismController.groovy
    @@ -121,10 +121,10 @@ class OrganismController {
                     organism.blatdb = organismJson.blatdb
                     organism.species = organismJson.species
                     organism.genus = organismJson.genus
    +                organism.directory = organismJson.directory
 
                     boolean directoryChanged = organism.directory != organismJson.directory || organismJson.forceReload
                     if (directoryChanged && checkOrganism(organism)) {
    -                    organism.directory = organismJson.directory
                         organism.save(flush: true, insert: false, failOnError: true)
                         sequenceService.loadRefSeqs(organism)
                     }

**Comment by cmdcolin** [comment]
I guess the idea of reloading the refseqs is a different problem, also brought up here...

**Comment by cmdcolin** [comment]
I think we should make the above change that I proposed, but rather than doing a loadRefSeqs during the update, do "validateRefSeqs" so that we know the updated data directory corresponds to the right sequences

**Comment by nathandunn** [comment]
I think that the "check organism" should be sufficient to validate ... do you want to fix it?:

    diff --git a/grails-app/controllers/org/bbop/apollo/OrganismController.groovy b/grails-app/controllers/org/bbop/apollo/OrganismController.groovy
    index a58c1c1..022d076 100644
    --- a/grails-app/controllers/org/bbop/apollo/OrganismController.groovy
    +++ b/grails-app/controllers/org/bbop/apollo/OrganismController.groovy
    @@ -121,10 +121,10 @@ class OrganismController {
                     organism.blatdb = organismJson.blatdb
                     organism.species = organismJson.species
                     organism.genus = organismJson.genus
    +                organism.directory = organismJson.directory
 
                     boolean directoryChanged = organism.directory != organismJson.directory || organismJson.forceReload
                     if (directoryChanged && checkOrganism(organism)) {
    -                    organism.directory = organismJson.directory
                         organism.save(flush: true, insert: false, failOnError: true)
   -                     sequenceService.loadRefSeqs(organism)
                     }

**Comment by nathandunn** [comment]
@childers   I think that this is working.  I won't put it on icebox until after Moni is done testing.

**Comment by childers** [comment]
No problem!

**Comment by monicacecilia** [comment]
I was able to change the directory to the "wrong" place. But I was not able to change it back to the "correct" directory.

![screen shot 2015-05-26 at 7 47 59 pm](https://cloud.githubusercontent.com/assets/1714621/7827794/450ea78a-03e0-11e5-8838-ba9b4c6da96c.png)

**Comment by monicacecilia** [comment]
Yep, works! I like the warning issued when you enter the wrong directory. 
![screen shot 2015-05-27 at 4 43 56 pm](https://cloud.githubusercontent.com/assets/1714621/7849909/b8a2c942-048f-11e5-82ae-137b1a17434b.png)

**Comment by cmdcolin** [comment]
RE: ccc4783

In my humble opinion the annotation count text field should also be removed, because the refresh button was only there to update the annotation count

**Comment by nathandunn** [comment]
For 2.0.0 this is fine.  These could be dynamic at some point, though.  I added it to #355.   I would do it there.
