### ISSUE TITLE
implement customizable naming schema for RepeatRegion and TranspoableElement

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#399]
If I create a repeat region or other non-transcript element it gives it an implied unique name.  Is this correct (with the realization that we need a better naming strategy) or should it give it the same name as the evidence it is being named for (if it is the only thing in the region). 

![screen shot 2015-05-20 at 12 01 23 pm](https://cloud.githubusercontent.com/assets/751274/7734025/055859bc-fee8-11e4-9520-1c4affe2b092.png)

**Comment by monicacecilia** [comment]
golly, this is so philosophical. good question. 
Short answer: yes, they should have their own name. 

Historically -because of current behaviour- I have advised curators to rename these features as soon as they place them up. Usually the community reaches a consensus on a prefix to name these, but Apollo is not automatically keeping track of how many of these have been created so there is no count. 

In an ideal world, what I would like to see is as follows: we could give the option to admins to create a name that includes the word "repeat" and then the species name (e.g first three letters of genus + first three letters of species like we do for i5K), and some numbering system that keeps track of how many of these have been annotated throughout the instance. That is, a repeat created in for the genome of Apis mellifera would have a name that looks like this: repeat_apimel_xxxxx

And something similar would happen for the transposable elements.

does this make sense?

**Comment by nathandunn** [comment]
I think it does.  I'm going to leave it as is, and then implement a separate naming schema for RR & TE.
