### ISSUE TITLE
(2h) List of tracks in "Tracks" tab should allow users to scroll to the end of the list and stay there

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#417]
When a list of tracks is longer than the visible space on the "Tracks" tab in the "Annotator" panel on the right, it is not possible to scroll down to the end and keep the bottom of the list in the field of view. The list "bounces" back to the top, whether or not a track is selected from the list. 

This also seems to be related to that "yellow highlight" at the top of the list after selection, or at the top of the list of Organisms after switching. 

Notice I selected a track down below, then the highlight went to the first track in the list. 
![screen shot 2015-05-27 at 10 19 18 am](https://cloud.githubusercontent.com/assets/1714621/7842728/dea7aa94-0459-11e5-9a54-4a9faf4184c3.png)

Also, at times it is quite difficult to "select" a track. Some times it is necessary to click several times (I am up to 9 times in the latest attempt) before the track is selected. It does not depend on "where" I click, I think it depends on "when", or "how soon after the tracks were loaded".

**Comment by nathandunn** [comment]
only occurs once you've highlighted something, otherwise fine.  It is the "yellow" highlight, not the selection one.  Very weird.

**Comment by cmdcolin** [comment]
Might want to consider a multiselect instead of a single select. The yellow highlight was a workaround for single selection model to check the checkbox with just one click



Sent from my Palm Pixi on AT&amp;T
On May 27, 2015 2:42 PM, Nathan Dunn &lt;notifications@github.com&gt; wrote: 


only occurs once you've highlighted something, otherwise fine.  It is the "yellow" highlight, not the selection one.  Very weird.

**Comment by monicacecilia** [comment]
This bug has now been corrected. 
Thank you!

**Comment by nathandunn** [comment]
Egads, thought I’d sent this awhile ago. 

It ended up I was issuing a “reload()” command continually.   The execute command returned true (thus continually reloading the track) instead of false.  Fixing this seemed to work, though we need to come up with a better model for doing this to check if the track had been loaded properly.   However, it works for now.    

Nathan
