### ISSUE TITLE
bulk load in ApolloV2

### ISSUE THREAD

**Issue by lfaino** [GMOD/Apollo#424]
Hi,
I was wondering if i can use the bulk script to import a gff file in Apollo V2.0. Apollo is using a mysql database and i have two organisms imported.

thanks
Luigi

**Comment by nathandunn** [comment]
Luigi, 

In theory yes.  I believe we've tested it. 

If you could post general questions to the mailing list (apollo@lists.lbl.gov) instead of github issues, I think it would be more valuable to the community.   You can subscribe here:

https://docs.google.com/forms/d/1PkOm2SKiaAiAhCaMHEc0YFwFZ9nrZaZkbt29R8PW-W8/viewform

Nathan
