### ISSUE TITLE
Stop codon retained

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#448]
I found an instance where a stop codon is retained in the export in WA2.0

    >SINV10883a-00001
    LVSMSMEYLVLRLRPLAGIRRAPDNLRRLRRETQLRPFYAHRVASRHVASRRASRHVSSRHFTSRHITATK*EDSTRRSVIECRSVDLGRRAILAKICWNFRLGIRVRKSHPVTPLRRHETVDRRPRRYVSRVLDVQVNVLLRLTEEVVYLLHGAERTDLLLGAVGDEPPGGAGRSSAVINDVRVTVGID

In WA1.0, this action results in a truncated protein

    >SINV10883-RA
    LVSMSMEYLVLRLRPLAGIRRAPDNLRRLRRETQLRPFYAHRVASRHVASRRASRHVSSRHFTSRHITATK

The * implies a stop. I just imported Sinv genome and annotations from hymenopteragenome.org and checked sequence.

**Comment by nathandunn** [comment]
This is FASTA export?   @deepakunni3   Do these all use the same mechanism?

**Comment by cmdcolin** [comment]
Yes Fasta export or "get sequence" function.

It is sort of a random aside, but the actual sequence for this gene from antgenome.org (i.e. the file was originally generated at antgenome.org and loaded at hymenopteragenome.org) is different from both of these: it marks this stop codon as an X and continues through it. This is a particular function that might be important


    >gnl|Sinv_1.0|SINV10883-PA
    LVSMSMEYLVLRLRPLAGIRRAPDNLRRXLRRETQLRPFYAXHRVASRHVASRRASRHVS
    SRHFTSRHITATK(X)EDSTRRSVIECRSVDLGRRAILAKICWNFRLGIRVRKSHPVTPLRR
    HETVDRRPRRYVSRVLDVQVNVLLRLTEEVVYLLHGAERTDLLLGAVGDEPPGGAGRSSA
    VINDVRVTVGIDXARSRSRRSXQPPAIAERNRGFGASVSHRLXLRVFKVYIGIALGVNRE
    SPATFLSDCEPRHRRRRRRRRHRRRPRVGARRRCPSGGGAQSGSVSRSDGDTGITGSRGD
    SHIGRIAVGSQADIEVPTCLRKFPAGKDGRGWRWGXGRSLACNQGVLCSQQQVAVSQKRT
    VRARRAARSESSGGRLGGGGDRQGHPLRFSXKGARRPIAAQDRPRRLVLDAXDRPRVAIV
    EIVXMMRLRRSLFPACR

**Comment by nathandunn** [comment]
Do you have time to look into it?

**Comment by cmdcolin** [comment]
Ya i'll check it out

**Comment by nathandunn** [comment]
thanks

**Comment by selewis** [comment]
Sounds like at least two problems. (the stop codon and the sequence
mismatch). Unless it is explicitly a stop codon read-through set by the
curator (which to my knowledge we don't support yet) then Colin is correct
- this is an error.


On Fri, Jun 19, 2015 at 3:24 PM, Nathan Dunn <notifications@github.com>
wrote:

> thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GMOD/Apollo/issues/448#issuecomment-113661108>.
>



-- 
In the long history of humankind (& animal-kind too) those who learned to
collaborate & improvise most effectively have prevailed - Charles Darwin

**Comment by cmdcolin** [comment]
I can make a new issue for the sequence mismatch as this is something Deepak and I discussed

**Comment by nathandunn** [comment]
@cmdcolin   I think that is correct.  I was hoping that it was just ignoring the stop codon on the get_sequence function, in which case it could just be fixed once.

**Comment by monicacecilia** [comment]
@selewis .... we have been supporting annotation of readthrough stops since September 2013. (2013-09-04 release) :expressionless:

**Comment by nathandunn** [comment]
@monicacecilia   . ..  @deepakunni3  said he would take a look at these, but please review if you have a moment.

**Comment by nathandunn** [comment]
just as a note, Chris Elsik though thought that this might be due to the tiny out of phase introns (e.g., 2-bases).

**Comment by cmdcolin** [comment]
I still haven't looked into the code to see what is happening, but this is what the CDS looks like when you translate it. it only gets about half the peptide translation, but it includes a stop codon which is the part that surprised me

![screenshot-www fr33 net 2015-07-09 15-32-56](https://cloud.githubusercontent.com/assets/6511937/8606265/0b8cb686-2650-11e5-9c9a-19b9649c170c.png)

**Comment by cmdcolin** [comment]
Edit: deepak has the scope. stay tuned

**Comment by deepakunni3** [comment]
@nathandunn @cmdcolin This bug is a simple fix but a tough one to find. 

The main problem was in readThroughStop argument for translateSequence() in FeatureService: 271
```
featureResidues = SequenceTranslationHandler.translateSequence(rawSequence,
standardTranslationTable, true, cdsService.getStopCodonReadThrough(cds) != null)
```

In Apollo 1.0.x, cdsService.getStopCodonReadThrough(cds) would have returned null if there was no read through stop codon set. 
In Apollo 2, the same method returns an empty arrayList which is not interpreted as null.
The fix is to replace this argument with a proper boolean value. 

I will be pushing the changes soon.

**Comment by nathandunn** [comment]
great.  Thanks for finding that.

**Comment by nathandunn** [comment]
@cmdcolin  @deepakunni3   I don't think I have an easy way to test this on the merge.  I'm going to have one of you retest this after the merge.   I tried to keep all of your changes.

**Comment by nathandunn** [comment]
@deepakunni3   
Just wanted to confirm that this was correct.  I set stop codon readthroughs on both of these.  In one case it includes the stop with a '*' and the other a 'U'.  This is HoneyBee Group 1.1 in both cases.   Anyway, I probably just need clarification.  No immediacy.  Thanks. 

<img width="935" alt="screen shot 2015-07-23 at 2 13 36 pm" src="https://cloud.githubusercontent.com/assets/751274/8862387/1fd23c06-3145-11e5-981c-69d288a7e64e.png">
<img width="740" alt="screen shot 2015-07-23 at 2 13 01 pm" src="https://cloud.githubusercontent.com/assets/751274/8862388/1fd54d56-3145-11e5-9ec2-6ec3082c6d04.png">

**Comment by monicacecilia** [comment]
@nathandunn The difference you see between the sequence in model GB42167 and GB42169 is due to the differences in the nucleotide sequence. Apollo is correctly reading the resulting sequence after setting the readthrough in each case. 

Your first example, GB42167, has a TGA stop codon, which Apollo correctly interprets as a selenocysteine (U) when the "Set stop readthrough" function is called. 
<img width="590" alt="screen shot 2015-08-03 at 5 21 29 pm" src="https://cloud.githubusercontent.com/assets/1714621/9050637/b1b3f3ae-3a04-11e5-88e7-ed66cdab36b8.png">
  

In the case of GB42169, the stop codon that Apollo has to skip is TAA, and it is, thus, correctly interpreted as a star (*).  TAA does not code for selenocysteine (and neither does TAG). 
<img width="589" alt="screen shot 2015-08-03 at 5 22 16 pm" src="https://cloud.githubusercontent.com/assets/1714621/9050643/d5adf278-3a04-11e5-9a4f-d84ddf2261fe.png">


=======


Dear @cmdcolin, in your sequence, there are more than one X, but according to what is shown in your report, Apollo2.0 only skipped through the first X, wrote a star (*) in its place, and stopped the sequence at the next X. (Btw, I'm scratching my head thinking whether Apollo2.0 skipped the first X but not the second one because there cannot be two readthroughs... it knows biology?! maybe... but I don't know where that rule is in the code). :)  (I am writing this so I can ask a question to Deepak - below).

<img width="603" alt="screen shot 2015-08-03 at 5 36 38 pm" src="https://cloud.githubusercontent.com/assets/1714621/9050772/adae46fe-3a06-11e5-9ef2-a1a52225534e.png">


Dear @deepakunni3, did you happen to test to be sure that the change you pushed took care of that? - i.e. reading "X" as stop and not going through it, unless the curator has set a Readthrough - and that this is correctly occurring in the updated SINV Apollo instance?

**Comment by deepakunni3** [comment]
@monicacecilia Hi Moni, I tested it just now.

Peptide sequence before setting a read through stop codon:
```
>0ed9376a-7114-4adc-a4f8-4be3d3a8856c (sequence:mRNA) 71 residues [Si_gnF.scaffold00779:3140270-3141606 - strand] [peptide]
LVSMSMEYLVLRLRPLAGIRRAPDNLRRLRRETQLRPFYAHRVASRHVASRRASRHVSSRHFTSRHITAT
K
```
Translation stops when it hits the first `X`.

Peptide sequence after setting a read through stop codon:
```
>0ed9376a-7114-4adc-a4f8-4be3d3a8856c (sequence:mRNA) 187 residues [Si_gnF.scaffold00779:3140270-3141606 - strand] [peptide]
MSMEYLVLRLRPLAGIRRAPDNLRRLRRETQLRPFYAHRVASRHVASRRASRHVSSRHFTSRHITATK*E
DSTRRSVIECRSVDLGRRAILAKICWNFRLGIRVRKSHPVTPLRRHETVDRRPRRYVSRVLDVQVNVLLR
LTEEVVYLLHGAERTDLLLGAVGDEPPGGAGRSSAVINDVRVTVGID
```
Translation reads through the first `X` and places a `*` and continues till it reaches the next `X`

@cmdcolin Thanks for updating the SINV browser. :)

**Comment by monicacecilia** [comment]
Brilliant. Thanks for the fix and confirmation. 
I'll create a new issue wrt the stop codons that do not code for selenocisteyne.
:dancer:

**Comment by monicacecilia** [comment]
@deepakunni3 something is still not working. 
The issue of the "stop" being mistakenly retained has been fixed (I'll close this issue again), but the issue of how Apollo is drawing this gene model (as shown in #453 ) is still incorrect in the SINV instance.
