### ISSUE TITLE
generate features from a (just added) BLAT alignment

### ISSUE THREAD

**Issue by selewis** [GMOD/Apollo#475]
Once an alignment is carried out we should be able to use it as the basis for a gene annotation

**Comment by cmdcolin** [comment]
We can definitely try and use @vivekkrish's add ons for this https://github.com/Arabidopsis-Information-Portal/Apollo/tree/extend-blat-plugin

**Comment by nathandunn** [comment]
From Vivek Krishnakumar,

>As Colin chimed in, yes this is definitely a useful feature to have in WebApollo, which is why we implemented it at the WebApollo hackathon last year (Jun 2014).
My implementation adds functionality to the pre-existing BLAT plugin, by temporarily storing the results of the spliced alignment (converted from psl to GFF3 format {match --> match_parts}), and dynamically loading the GFF3 as an evidence track containing draggable features.

>My code is available in this fork of Apollo: https://github.com/Arabidopsis-Information-Portal/Apollo/tree/extend-blat-plugin. One caveat is that this code was implemented in the WebApollo 1.0 branch prior to the refactoring done by @nathandunn (which started sometime in Sep 2014). We haven't yet tried to reconcile this code with this refactored branch.

Just adding these comments, because I think that being able to capture the metadata (somehow) in this process is really important, which is what I think @selewis is implying.

@monicacecilia 
>>Yes, when you generate a track of hsps from sequence similarity searches, you can use those to create annotations. For example the BLAST hsps we have over at i5K@Workspace at NAL.
However, in Apollo BLAT does NOT generate a track, but a list of hsps. Users are able to use all other available evidence in the region as starting material to create their annotations - Michael would be able to, if VectorBase had not made some of the scaffolds unavailable, actually. In the absence of supporting evidence, I stand in my position that we should NOT allow users to create annotations out of thin air. Importing Gff3 is cheat enough hehe, we can just let them do a "right click" operation to invent a gene model where non is supported to be. :)


@selewis
>There we concur. One of the problems with this fast-and-loose approach (as described above) is that the evidential basis for the annotation is transient. The one single user sees it, but no one else does, it's lost by the time of the next user session. The above solutions are technical are quite feasible and have the added benefit of giving power to the user. However it leaves the door wide open to non-reproducible science. Ideally I'd like a solution that let's us have it both ways. *Let the users do what they need to do, but somehow capture the evidence they provided as well.*
