### ISSUE TITLE
Insertion of sequence alteration on negative strand creates *upstream* non-canonical splice sites

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#531]
Found by @selewis   while looking at BRCA1 transcripts with multiple isoforms:

http://icebox.lbl.gov/Apollo2/annotator/loadLink?loc=chr17:43125029..43125369&organism=5402342&tracks=GenBank TopLevel MRNA

So, for BRCA1-023-00001 if you create the transcript and set the downstream donors at the 5' end, it will do this, but with no non-canonical splice site. 

However, if you add a sequence alteration (at any point), you will have a non-canonical splice site (upstream).  When you create the donor, the non-canonical splice site remains.  FYI @deepakunni3  @monicacecilia .

**Comment by selewis** [comment]
It's on the reverse strand, perhaps that is part of it?

**Comment by nathandunn** [comment]
Hmm . . I still couldn't reproduce it even with the BRCA transcripts (23 & 1) it always seemed to reproduce the correct splice sites.    I'm sure that there is an edge-case in there, just not quite sure how to find it.

**Comment by selewis** [comment]
It was the most 5' exon (on the minus strand). Did you try it with that
particular exon?

**Comment by nathandunn** [comment]
@selewis   it ended up being the sequence alteration you had added.   It adds it before you add the donor.     If you add the alteration and then the transcript you end up with the non-canonical splice site.  
Seems like the CDS should be re-calculated to account for that or the Non-canonical splice site is incorrect.

![screen shot 2015-08-10 at 6 51 46 pm](https://cloud.githubusercontent.com/assets/751274/9188430/f1f55ab6-3f90-11e5-955b-bad3f373d098.png)

**Comment by selewis** [comment]
I hadn't added any sequence alteration.

Someone else perhaps?
If it was added why wasn't it visibly flagged (don't see it in this screen
shot either)

And even if I had added it then the code for finding the next donor site
should take this into account and still find a valid site.

**Comment by nathandunn** [comment]
Insertion of sequence alteration on negative strand creates *upstream* non-canonical splice sites:

<img width="477" alt="screen shot 2015-08-11 at 2 02 28 am" src="https://cloud.githubusercontent.com/assets/751274/9194015/0fe3113a-3fcd-11e5-9a65-82b51502a965.png">

<img width="487" alt="screen shot 2015-08-11 at 2 03 08 am" src="https://cloud.githubusercontent.com/assets/751274/9194026/219a3bb0-3fcd-11e5-9f87-ea6955e39cfe.png">

**Comment by nathandunn** [comment]
I *think* what needs to happen is that we need to use @deepakunni3  sequence alteration coordinate transform code to properly get the offsets.  If they are in the intron they should be ignored when doing the calculation, though somehow we need to pick up the proper offset.   I am wondering how to handle this in relation to #431.    FYI @cmdcolin  . . 

<img width="471" alt="screen shot 2015-08-11 at 7 26 49 am" src="https://cloud.githubusercontent.com/assets/751274/9200025/a6d95b80-3ffa-11e5-9302-2b31f4c249f5.png">

**Comment by cmdcolin** [comment]
If we were just considering frameshifts, it wouldn't need to consider introns since of course it is just the translation, but the splice sites are "in the intron". Therefore, you need to consider the alterations in the intron that might affect the splice sites.

**Comment by nathandunn** [comment]
@cmdcolin   Like you said, you need to consider the alterations in the introns.  Specifically because the residues do as well, and you have to handle that offset accurately.   Anyway, I'm updating for a smaller Transcript (just 3 exons).

**Comment by selewis** [comment]
alterations affect the genome - whether or not it is within/outside of any
given feature is irrelevant. Order of any operation is: First get the
genomic sequence altered, then remap features onto altered genome and
proceed as usual. It's a kind of coordinate transform/projection.

(as @cmdcolin said)

**Comment by selewis** [comment]
You're right about the *upstream* part.

That's weird and bad.

A sequence alteration always affects *both* strands.

There physically isn't any other way to do it. The two strands of DNA are
paired, there is no way for only one strand to be altered and the other not
to be affected (it'd be kinky at the least).

That said, given an indel at point X on the genome this will affect all the
features located 5'wards on the plus strand and all the features 5'wards on
the minus strand (i.e. in the opposite direction)
(speaking of stranded features)

>>>>>>X>>>>>>>
<<<<<<X<<<<<<<

**Comment by monicacecilia** [comment]
What I observed while trying to recreate this bug. 

I am able to recreate non-canonical splice sites appearing when creating genomic deletions and insertions; they are *sometimes* accurately accounted for in transcripts in the forward strand - and some times introduced in what seems to be a random manner (for example see Group1.10 GB40804; create genomic deletion length = 2 at coordinate 191,162; see image), and they are (so far) always inaccurately accounted for in transcripts in the reverse strand. As described in #431, Apollo is not properly drawing the resulting transcript. 

In this image Apollo is drawing non-canonical splice site warnings, despite the fact that it is recovering the CDS without problem, and producing accurate FASTA and GFF3 files.
![screen shot 2015-08-11 at 6 23 34 pm](https://cloud.githubusercontent.com/assets/1714621/9214737/3e60d36a-4056-11e5-9edb-98cc455d48cc.png)

In some cases it is also failing to recalculate the CDS 

Steps to see the bug: 
1. create annotation
2. create modification to sequence; e.g. deletion, insertion.
3. result: shift in coordinations for exons in gene model located to the right (looking at screen) of the alteration, regardless of strandedness. That is okay for the forward strand, but it is incorrect for the reverse strand. 

The creation of non-canonical splice sites in the downstream exons happens because the operation is shifting the CDS overlapping the change. Because transcription occurs in 5' --> 3' direction, the results of the sequence alteration should be captured in the remaining exons of the transcript, on coordinates located to the 3' end of the alteration, regardless of the strand. (@selewis , you meant 3' (not 5'), correct?)

Thinking of the transcript as a concrete unit, a sequence alteration should accurately modify the overlapping coding sequence of the transcript, starting on the coordinate where the alteration is created and until the "stop" signal. A sequence alteration does not mean the re-organization of all coordinates across the scaffold but the re-calculation of the CDS over the alteration, taking into consideration the alteration at that coordinate. It should create a transcript with a sequence alternative to the underlying assembled scaffold/group (Ref Sequence in Apollo).

**Comment by selewis** [comment]
I think I'd like a code review on the entire coordinate issue.

Based on the small amount I've heard on these threads in GitHub I'm afraid
that the code is handling these in a piecemeal fashion rather than in a
generalized way. This shouldn't be hard.

This may ultimately require a big refactoring

(yes, Moni and I agree on the biology. I was trying for that with my ascii
art)

**Comment by nathandunn** [comment]
I'm confused.  This was not ready to test.  @cmdcolin  just fixed this.  I'll test it tomorrow morning and retag with #534.   

We should refactor this code, however, we thought it was in working condition, but there were several deficits that @deepakunni3 fixed from WA1.  We did not intend refactor it, but it might be good to look at for 2.0.1 or 2.1 now that we have many more regression tests.

**Comment by nathandunn** [comment]
I see, @monicacecilia  you were evaluating the bug.  My bad.  The single-offset makes sense as that is what I saw in my testing.  Looks like @cmdcolin fixed it (knock on wood).

**Comment by selewis** [comment]
yep - knock on wood!

**Comment by nathandunn** [comment]
@cmdcolin   This looks good.  I was also able to set the upstream and downstream non-canonical splice sites donation / accepting also works.

**Comment by cmdcolin** [comment]
Thanks.  I think  @selewis was correct in this statement

>Order of any operation is: First get the genomic sequence altered, then remap features onto altered genome and proceed as usual. It's a kind of coordinate transform/projection.

That is indeed what we did.

So, ya, code review sounds good too, if there is ever a chance to do that let me know. Might also look at SequenceAlterationInContext code.

**Comment by monicacecilia** [comment]
@nathandunn are these changes already available on icebox? (if so, then this bug has not been fixed.)

**Comment by nathandunn** [comment]
no, they are not on icebox

**Comment by monicacecilia** [comment]
Oh, the "ready" label was misleading.

**Comment by monicacecilia** [comment]
Sequence alterations no longer cause changes in exon upstream (towards N-terminus, 5') of the protein. Brilliant! :dancer: 

The code review that @selewis suggested should still take place.

**Comment by nathandunn** [comment]
I'll create an issue for the the code review.  This needs to happen for 2.1. .

**Comment by monicacecilia** [comment]
deal.
