### ISSUE TITLE
provide CRAM support for Apollo

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#550]
Technically this is a JBrowse issue, but I think we'd wanted it for human:

https://github.com/GMOD/jbrowse/issues/546

**Comment by cmdcolin** [comment]
I have basically gotten this compiled to emscripten to the point where i can run some htslib libraries (i.e. the library with CRAM support, written in C)

so now, there are implementation questions. there are basically two paths. using some of the existing code that htslib has to get networked files already, or to use custom code to get networked chunks of files and then getting htslib to interpret chunks. 


for using the "existing htslib code" approach, this is how it I envision it

background) the default method that htslib uses to read files from the web are with typical POSIX socket code.
so:
this means that after compiling through emscripten, these are converted to use websockets (pretty cool). but, it also means that the websocket methods should basically be asynchronous or non-blocking sockets because javascript is a very asynchronous language.


For the "custom code" approach, this is more unexplored, but basically we would have to use have to find the interface from javascript to C, and this is somewhat uncharted territory because the htslib people say some of their internal data structures haven't been finalized. they are working on making more "public methods" for cram but it is not sure yet (i saw commits for this to htslib repository only started recently)

In either case, I still think that using htslib via emscripten is a good way to leverage existing efforts for the formats. re-implementing in javascript might be "elegant" but also too time consuming, there are advanced compression algorithms in cram that might make it difficult.

As i noted in the jbrowse thread, i can add some instructions for what i have so far too

**Comment by cmdcolin** [comment]
I went ahead and compiled some doxygen for htslib since there isn't yet a defactor API reference

http://cmdcolin.github.io/htslib_docs/files.html


One note that I found interesting in cram.h says

    "Consider using the higher level hts_*() API for programs that wish to be file format agnostic (see htslib/hts.h)."

This made me consider kind of going back to the "high level" hts functions, and hence, simply using the websocket approach at the same time

Still, reviewing the available api functions might be useful

**Comment by nathandunn** [comment]
https://github.com/igvteam/igv.js/issues/247  

We could do what they do, using CRAM as a REST track and then using the java htslib library to read BAM.

https://github.com/samtools/htsjdk/blob/master/src/main/java/htsjdk/samtools/CRAMFileReader.java

To emulate what our BAM reader does already (https://github.com/nathandunn/Apollo/blob/bam_integration/grails-app/controllers/org/bbop/apollo/BamController.groovy)

**Comment by nathandunn** [comment]
This is done as part of the JBrowse upgrade.
