### ISSUE TITLE
fail to call updateUser webservice

### ISSUE THREAD

**Issue by ifishlin** [GMOD/Apollo#634]
Hi

I called updateUser webapi to update user information.
Although, the record was changed correctly in DB, but I always get a error message

![image](https://cloud.githubusercontent.com/assets/9721827/10768901/b6efa92e-7cb9-11e5-8b0d-f430a5ef657b.png)

== Here is my script ==

curl -b cookies.txt -c cookies.txt -X POST --header "Content-Type:application/json" --data "{"userId": "163", "firstName":"Bob2", "lastName":"Smith2", "email":"bob2@admin.gov", "role": "user", "username": "R2D2@i5k.org", "password": "demo"}" http://localhost:8085/apollo/user/updateUser

and this also happened when I called it in python script.

**Comment by ifishlin** [comment]
I also call createUser and deleteUser in the same way, but there all work well.

**Comment by nathandunn** [comment]
@ifishlin   My checkin of #dc66dao was slightly unrelated (but still a bug fix).   

Are you seeing any errors in the log?

**Comment by ifishlin** [comment]
@nathandunn 

I'm sorry , where can I find the log?

**Comment by nathandunn** [comment]
If you’re using tomcat its typically in catalina.out . . 

If you’re in dev-mode it should be wherever you’re grails console is. 

If you want to see more debugging (at least temporarily), you can edit your Config form:

 warn ‘grails.app’ 
to 
debug ‘grails.app’

(just don’t check it in that way)



Nathan

**Comment by ifishlin** [comment]
Hi 

I correct the code (about newpassword)
There is no error msg on grails console
The error msg I showed you is the return of curl and it still happened.

**Comment by ifishlin** [comment]
I switch to DEBUG mode, and got three line log when I run curl.
is there something wrong with "organism null"?

2015-10-27 15:57:41,738 [http-bio-8085-exec-9] INFO  apollo.DbRealm  - Attempting to authenticate R2D2@i5k.org in DB realm...
2015-10-27 15:57:41,742 [http-bio-8085-exec-9] INFO  apollo.DbRealm  - Found user 'R2D2@i5k.org' in DB
2015-10-27 15:57:41,751 [http-bio-8085-exec-9] DEBUG apollo.PermissionService  - passing in an organism null

**Comment by ifishlin** [comment]
I'm sorry, I miss first line.

2015-10-27 15:59:59,800 [http-bio-8085-exec-10] DEBUG apollo.PermissionService  - creating session with found json object R2D2@i5k.org, demo
2015-10-27 15:59:59,801 [http-bio-8085-exec-10] INFO  apollo.DbRealm  - Attempting to authenticate R2D2@i5k.org in DB realm...
2015-10-27 15:59:59,804 [http-bio-8085-exec-10] INFO  apollo.DbRealm  - Found user 'R2D2@i5k.org' in DB
2015-10-27 15:59:59,814 [http-bio-8085-exec-10] DEBUG apollo.PermissionService  - passing in an organism null

**Comment by nathandunn** [comment]
If you’re an admin user there should be no issues.  Let me look a little deeper.

Nathan

**Comment by ifishlin** [comment]
I am sure that I used a Admin account.
I think there is no problem in function updateUser, but there somehow existed another process which asks for "/WEB-INF/grails-app/views/user/updateUser.gsp".

I got http 404 from both python and curl.

**Comment by nathandunn** [comment]
render new JSONObject() as JSON should imply that its returning as JSON .  . . 

most likely what is going on is that there is a save that is throwing an error . .. (maybe) 

Do you not see:             

log.info "Updating user"

or             

log.info "Updated user"

**Comment by ifishlin** [comment]
No, only four lines when I call updateUser.

**Comment by nathandunn** [comment]
This is what I see:

2015-10-27 13:28:18,104 [http-bio-8080-exec-15] INFO  apollo.UserController  - Updating user
2015-10-27 13:28:18,112 [http-bio-8080-exec-15] INFO  apollo.UserController  - Updated user


When I run this:

curl -X POST --header "Content-Type:application/json" --data "{"userId": "6569", "firstName":"Bob2", "lastName":"Smith2", "email":"test123@test.com", "role": "user", "username": "ndunn@me.com", "password": "demo"}" http://localhost:8080/apollo/user/updateUser


This code is run by the admin interface as well.   What happens if you make a change to the user using the admin panel?

You should see similar JSON passing through. 

Nathan

**Comment by ifishlin** [comment]
My apollo was downloaded at Sep 10, should I try the latest one?

**Comment by nathandunn** [comment]
Yeah . . if you are writing scripts against it, then I would pull out of master or 2.0.1-RC4.   We’ve fixed quite a few things.  

All of these changes should be rolled into the eventual 2.0.1 release, which should have notably more web services and better-documented web services.  

I think that we can probably close this for 2.0.1 since this is something we fixed there. 

Nathan

**Comment by ifishlin** [comment]
Hi, I see the problem

My apollo version didn't  "render new JSONObject() as JSON" at final

**Comment by nathandunn** [comment]
Found in 2.0.0 . . fixed in 2.0.1

**Comment by nathandunn** [comment]
Yep!
