### ISSUE TITLE
allow annotators to choose which model to get functional annotations from during a merge operation

### ISSUE THREAD

**Issue by mpoelchau** [GMOD/Apollo#646]
Hi everyone,

An annotator has mentioned that Web Apollo's behavior to adopt functional annotations (e.g. name) from the left model during a merge operation can be a bit bothersome if you'd like to retain the information from the right model, instead (e.g. if you've spent a lot of time adding functional information to the right model, then realize you need to add an extra exon). Are there any future plans to allow the annotator to choose which model the functional annotations will come from?

Thanks!

Monica P

**Comment by nathandunn** [comment]
@mpoelchau  If you have a proposal for the interface that would help.  My two thoughts:
1 - on the interface instead of "merge" have a drop-down with the options: merge-> left , right, combine . . . 
2 - on the interface add the options directly in the interface (a little bit cluttered I think)
3 - have a popup (yuck)

@deepakunni3  If you have any thoughts . . . This won't be in the 2.0.1 milestone, but we probably need to allow a bit of this arbitrary flexibility either way.

**Comment by nathandunn** [comment]
I'm not sure if we'll need something for splits as well.

**Comment by nathandunn** [comment]
@monicacecilia types: The behaviour has now been updated: almost all metadata from both gene models will be merged into the resulting gene model. 'Undo' splits back the original data to the source gene model.  The exception is the gene name. In every case, the gene model resulting from a 'merge' function will adopt the name of the left-most gene model.

**Comment by nathandunn** [comment]
From conversation with @deepakunni3  wanted to clarify that we are merging ONLY the metaata from the gene models

**Comment by monicacecilia** [comment]
Copy that. This is not true for other types of genomic elements.
