### ISSUE TITLE
look at boiler for BAM visualization 

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#650]
Pritt, M.J.
Boiler—A compression tool for BAM files supporting fast, accurate queries
poster

Its about a 1-10 compression and is a lossy format, but it stores edge boundaries and coverage density.  Not a replacement, but it could lead to a better visualization and optimized visualization performance.

**Comment by nathandunn** [comment]
Looking at CRAM3 . . obviously a nice API (well-supported) and lossless when coming in from BAM.   It looks as though the compression is around 100% (twice as small).  More of interest to me is the reduction (and potential visualization) of the reduced data.

**Comment by cmdcolin** [comment]
I am still holding out for CRAM. I don't fully undestand the implications of boiler but they have a poster here (presumably it was at genome informatics as well?) http://idies.jhu.edu/Media/Default/PDF/IAS2014Pritt.pdf

I also have some notes on the htslib to javascript here
https://gist.github.com/cmdcolin/066b477b6938560f9634

Getting close...I think I just need to design some client side code that uses htslib now because the conversion to javascript is complete

**Comment by nathandunn** [comment]
I still think we should provide CRAM support.  In 2.1 the way I’m handling BAM files (using the htslib API) should make providing CRAM support pretty trivial. 

Nathan

**Comment by cmdcolin** [comment]
I don't think that using htslib on the server side really gets the benfits of using the CRAM format, because then you transmit uncompressed over the wire (?)

The client needs to understand the cram format

**Comment by nathandunn** [comment]
I believe CRAM would be faster to do lookups and smaller on disk.   Either way, we are stuck with doing the server-side transform.

My hope is that Boiler will also suggest an alternate visualization with a much higher signal to noise ratio.  It won't replace BAM or CRAM, especially since its lossy.

**Comment by nathandunn** [comment]
FYI finally published https://github.com/jpritt/boiler by @jpritt .  Will have to evaluate yet.
