### ISSUE TITLE
verify that the version goes to the correct place now.

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#67]
6. Is this intentional? The Help/Version: 1.0-SNAPSHOT menu sends users to 
https://github.com/GMOD/Apollo/commit/master
This is not useful information.

**Comment by nathandunn** [comment]
I need to review this.

**Comment by monicacecilia** [comment]
@nathandunn 
On both Staging and Demo instances, the "Get Version" option from the "Help" menu sends users to https://github.com/GMOD/Apollo/releases/. On the Apollo2 demo, the URL hyperlinked in front of the "Version" field goes to https://github.com/GMOD/Apollo/commit/master 

That was the old behavior, back when this issue was created (I think). Now Apollo2 needs to be updated to reflect the changes already present on Staging and Demo.

**Comment by monicacecilia** [comment]
fuhggeddaboudit!

**Comment by monicacecilia** [comment]
Brilliant. Let me know when you update Annotator (Apollo2) and we can check and close this one.

**Comment by monicacecilia** [comment]
Working as expected.
