### ISSUE TITLE
Pinstripes disappear in small scaffolds.

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#709]
When looking at short scaffolds, the pinstripes disappear. It is clearer when switching to 'Dark' scheme viz.

<img width="979" alt="screen shot 2015-11-20 at 1 52 38 am" src="https://cloud.githubusercontent.com/assets/1714621/11296834/6f52062a-8f29-11e5-9f09-0620a23851cf.png">

A number of errors are visible in the console - some are specific to my installation of Chrome, others are also visible on "normal"-running pages. But the two errors at the bottom show 404 errors when trying to pull information about the available tracks. All a bit puzzling.

<img width="1344" alt="screen shot 2015-11-20 at 1 54 51 am" src="https://cloud.githubusercontent.com/assets/1714621/11296926/ea28f7a0-8f29-11e5-9dbb-b99a4d47cdfd.png">

I am using the citrus psyllid Apollo instance (v1.0.4) from i5K Workspace@NAL (@mpoelchau @childers @ifishlin) for the citrus psyllid genome. _Diaphorina citri_ Scaffold ID: gi|645133236|ref|NW_007539427.1

Longer scaffolds, e.g. gi|645508407|ref|NW_007377442.1, are normally displayed.

**Comment by mpoelchau** [comment]
Hi Moni,

Sorry the pinstripes aren't working for you. Is this still the case? I'm going to answer with a completely unhelpful 'But I can see them'... They are showing up for the same scaffold and resolution on firefox and chrome. 

![screen shot 2015-11-20 at 10 04 45 am](https://cloud.githubusercontent.com/assets/5487172/11306309/374b71c2-8f6e-11e5-92fd-e32e62fe6051.png)


That's still kind of worrisome, even if it was a temporary thing.



As for the 404 errors - I see these as well on chrome. I'm not sure why they're occurring - perhaps because there are no features on this small scaffold? As you mentioned, the 404 errors disappear when viewing a larger scaffold with features in each track (e.g. gi|645508417|ref|NW_007377440.1|).

**Comment by cmdcolin** [comment]
This bug should be fixed upstream in jbrowse in the next jbrowse release. See https://github.com/GMOD/jbrowse/issues/514

The observed differences between browsers is can probably be explained if interested, but i think it suffices to say that this will be fixed in later versions

**Comment by nathandunn** [comment]
Thanks . . . . I'll mark it as blocked and it can be fixed there.

**Comment by monicacecilia** [comment]
Thanks! :+1:

**Comment by nathandunn** [comment]
@monicacecilia types: this is already fixed in JB.
