### ISSUE TITLE
"Bookmarkable" URL routes

### ISSUE THREAD

**Issue by erasche** [GMOD/Apollo#722]
I would like to be able to hand out single URLs to users that would result in them opening apollo with a specific organism, perhaps to a specific location/specific set of tracks, much like how JBrowse functions. Ideally sending one of my users a link like `https://fqdn/apollo/annotator/index?genome=NC023313&location=ctg1:1000:2000` will launch them into the correct organism, track, and location

(Is this a dupe of https://github.com/GMOD/Apollo/issues/684? I can't quite tell, sorry)

My specific use case is we have automated pipelines in Galaxy preparing a JBrowse instance and loading the data into Apollo on behalf of the user. I'd like to output a simple "Click this link" at the end of the pipeline for them to click and follow into Apollo.

**Comment by nathandunn** [comment]
Yeah, the terminology is kind of confusing since we are using it in the sense of projections as well.

I think we are already doing this, however.  In 2.0.0 (and shortly in 2.0.1 as a popup) there is a link icon that generates the proper "apollo" or "jbrowse" (public) link:

![screen shot 2015-12-07 at 2 41 46 pm](https://cloud.githubusercontent.com/assets/751274/11642062/bd048ea4-9cf0-11e5-9045-df0b220d2f3d.png)

I'll close this, but if it doesn't work, let me know and we can get it fixed.

**Comment by erasche** [comment]
Oh jeez, can't believe I didn't notice that before. I'm used to the JBrowse one and didn't notice that it'd moved an inch to the right. Brilliant, thanks1
