### ISSUE TITLE
Extensions to BLAST and InterProScan

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#723]
- [ ] BLAST
- [ ] InterProScan
#### This comes from a message received from Mohammed Khalfan (DNA Subway):

In the original [desktop] Apollo we had a way to send sequences to blast and interpro scan, would you be able to tell me where to begin on integrating this in web Apollo? Are you guys working on this by any chance?

Thank you very much,
Mohammed

Mohammed Khalfan | Sr. Bioinformatics Developer | www.dnalc.org

---
#### Comments:

We have already seen implementation of BLAST within Apollo. @alpapan implemented extensions (through Web Services (?)) for one of the species from the i5K pilot. See example in figure:

![screen shot 2015-12-09 at 8 47 46 pm](https://cloud.githubusercontent.com/assets/1714621/11707242/7cc133f2-9eb6-11e5-9e86-1a033fa3786a.png)

I don't know if this is publicly available, but perhaps @mpoelchau or @childers know where we could find it.

**Comment by tengp** [comment]
Hi there,

I'm curious whether this function for submitting the sequence to Interproscan and BLAST in the new Web Apollo is public available now? Thank you.

Best,
Pan

**Comment by cmdcolin** [comment]
I think the exact types of configurations in these pictures is not in the core codebase, but Apollo 2.0 allows configurability of "sequence_search_tools" in the config, which can allow you to customize the search services. For example by default the BLAT one is loaded, but a BLAST config is available too

https://github.com/GMOD/Apollo/tree/master/src/groovy/org/bbop/apollo/sequence/search/blast

I don't know how ambitious you are for implementing your own custom adaptors too and I can add some more suggestions if interested. It's possible that configuring the right click that way could be added too, some work has been done on that

**Comment by tengp** [comment]
We're using the old Apollo for now in DNA subway website, but we're trying to move forward to web apollo. It'll be very useful both for the teachers and the students if both BLAST and InterproScan functions are enabled in Web Apollo. What suggestions do you have if we want to implement these by configuring right click? Thanks.

Best,
Pan

**Comment by cmdcolin** [comment]
I'd say the two options that are available, for example, to query the InterPro REST API, are to

1) Customize the javascript for the right-click menus (requires manually changing code manually) to query (a) first get the sequence of the feature using getSequence on Apollo's web service and then (b) sending an API request to InterProScan via REST http://www.ebi.ac.uk/Tools/webservices/services/pfa/iprscan5_rest
2) Create a custom Java class for use with the sequence_search_tools configuration that does something similar to query the InterProScan REST API. The sequence_search_tools adaptors wouldn't display in the right-click menu, but they would display in the Tools->Search sequence dialog box, and of course you could just cut and paste the sequence from a feature into there


Both of them are pretty similar in terms of effort :) I think that the configurability of sequence_search_tools is an advantage since it doesn't involve editing core webapollo code, but as mentioned, we could also make the right-click menus more configurable in the future

**Comment by tengp** [comment]
Thank you so much for your reply. It's very helpful. I noticed that there's a MenuItem.js file under /jbrowse/src/dijit/ folder for building the right click menu on dijit/templates/MenuItem.html. But I couldn't find where to add a new item, say "submit to InterProScan" to the menu. Is there a config file for this? 

Best,
Pan

**Comment by cmdcolin** [comment]
I would look in AnnotTrack.js https://github.com/GMOD/Apollo/blob/master/client/apollo/js/View/Track/AnnotTrack.js#L4332-L4351

The client/apollo/js folder is the "Apollo JBrowse plugin" folder containing all the customizations for the annotation track, and the part that I linked to shows the right-click code.

**Comment by nathandunn** [comment]
The Annotation tracks / AnnotTrack.js  is for the Annotation track at the top: 

If you want to do the same for evidence you’ll need to edit the DraggableHTMLFeatures and CanvasHTMLFeatures in the same manner. https://github.com/GMOD/Apollo/blob/master/client/apollo/js/View/Track/DraggableHTMLFeatures.js#L1255 <https://github.com/GMOD/Apollo/blob/master/client/apollo/js/View/Track/DraggableHTMLFeatures.js#L1255>  . .  however, I would start with AnnotTrack.js per @cmdcolin's recommendation.  

Nathan

**Comment by tengp** [comment]
Thank you @cmdcolin and @nathandunn ! This is super helpful !

**Comment by nathandunn** [comment]
@monicacecilia types: @alpapan, would it be possible for us to please get hold of your webservices BLAST extensions code?
