### ISSUE TITLE
(2d) isoforms should belong to the same gene model, removing overlap should result in transcripts that belong to separate gene models

### ISSUE THREAD

**Issue by mpoelchau** [GMOD/Apollo#73]
Hi there,

We've noticed a number of issues pertaining to the correct gene parent assignment of multiple mRNAs. I have identified one source for these errors. If a user creates multiple annotations, then modifies them such that they do not overlap anymore, the original gene parent assignment is retained, instead of assigning a new gene parent ID. See the attached image for an example. 
![untitled 2](https://cloud.githubusercontent.com/assets/5487172/5018163/17e46a12-6a82-11e4-8880-fec5388ecc51.png)

Thanks for looking into this!

Monica P

**Comment by nathandunn** [comment]
Need to add another call after other calculations are done to verify that we verify that we have not left our current isoform siblings or that we have just joined some and we should merge genes (always taking the one on the left). 

1 - using OrfOverlapper, find other isoforms
2 - for each isoform, confirm that they belong to the same gene  (if not, we merge genes)
3 - confirm that no other non-overlapping isoforms have the same gene (if not, we create a new gene)

Trying to iterate over what functions could cause this:
- any time we recalculate the CDS on a transcript (featureService.calculateCDS()) . . .  (already done for addTranscript and addFeature)
- setExonBoundaries
- addExon
- deleteExon
- setAcceptor / Donor  (downstream / upstream)
- setTranslationStart/End

**Comment by nathandunn** [comment]
Should add functional tests ala:

http://aruizca.com/integrated-vs-functional-testing-how-to-test-rest-apis-in-grails-using-spock/

https://github.com/craigatk/geb-example

**Comment by nathandunn** [comment]
Using https://trello.com/b/ns56thpP/web-apollo to track the many possibilities.

**Comment by monicacecilia** [comment]
In other words: gene parent ID should not be retained without overlap among mRNA children and vice versa.

**Comment by monicacecilia** [comment]
We moved this issue to 2.0.1 because this is "new" functionality - not currently available on v1.0.4. @nathandunn wants to dedicate more attention to this.

**Comment by selewis** [comment]
I urge that this be fixed ASAP

1. It's not 'new' functionality. It's fixing something that is Broken. It's
a bug fix.

2. It is not simply overlap among the mRNAs. Specifically it is *overlap of
the CDS region of the mRNAs, in the reading frame.* Thus, UTRs of the mRNAs
might overlap, but that wouldn't make them part of the same gene. Or (a
tiny number of very rare cases) the CDS portion of the mRNAs might overlap,
but none of these portions is translated into any shared protein sequence.

**Comment by nathandunn** [comment]
If we have time for the 2.0.0 release we will pull it forward.  I had already started on this with the overlapper you described.  We will cross our fingers. 

Nathan

**Comment by nathandunn** [comment]
"Monica: we've ran into a few cases where the annotator adds information into the gene model, on the "gene" field. And then that gene parent is applied to an isoform that should not be. 
where two isoforms share a gene parent that shouldn't. probably happens because the two genes used to be isoforms but now they are not. the inherited "gene" information is kept -- and we need to not have the same gene parent info. 
so when we split this in our own scripts and id those cases, the question is : where does that gene parent info goes? model 1 or 2?
if you dynamically reassign the parent to one of the two? where should it go? 
Monica: we could we at least have a pop-up warning that "you are now splitting parents", where are you assigning it and revisit the parents in both models."

**Comment by monicacecilia** [comment]
From @mpoelchau 
We've ran into a few cases where the annotator adds information into the gene model, on the "gene" field, and then that gene parent is applied to a different transcript that should not be its isoform. 
When two isoforms share a gene parent that they shouldn't share: this probably happens because the two transcripts used to be isoforms of the same gene, but they are no longer so. The inherited "gene" information is kept -- and we need to not have the same gene parent info. 
So when we split this in our own scripts and identify those cases, the question is: where does that gene parent info goes? Does it go to model 1 or 2? And if you dynamically reassign the parent to one of the two, where should it go? 
Monica adds: we could at least have a pop-up warning that says "you are now splitting transcripts and as a result these will have different parents", where are you assigning it and revisit the parents in both models.   
The same thing happens in reverse case: two separate genes that need to be merged into one gene. They both have gene parent information, what do you do with one of the two?

**Comment by monicacecilia** [comment]
This is not ready yet. The resulting behavior is still not completely following the biology. A few things still need to be corrected: 

- [ ] When two splice forms (isoforms) of the same gene overlap on their coding sequence (CDS) - even if the overlap is just a few amino acids-, they should have the same parent gene. This should always be true. 

I just discovered that when you have two splice forms that overlap on their coding sequence, and you split one of them in two, the third fragment receives a different parent - even though its Coding Sequence overlaps with that of one of the original splice forms.

In the figure below: GB51343-00001 and GB51343-00002 were two exact copies of the same gene and their CDSs completely overlapped, from _Start_ to _Stop_. After _Split_ between the 5th and 6th exon, Apollo created and assigned a new parent gene to the isoform located to the 3'-most end of the resulting two models (this is a gene transcribed from the forward strand, so is the one on your right), even though its CDS overlaps a large portion of the other isoform - it was labeled as GB51343-a-00001. You can see evidence of the rename and removal of the common parent by the information displayed on the _Information Editor_ when using the right-click menu on one of the original isoforms.

This is incorrect, this last gene model is also an isoform of this gene and it should also have the same gene as its parent; its name should have been GB51343-00003. And the last one in the figure, labeled as GB51343-a-00002 should be labeled GB51343-00004 instead.

![screen shot 2015-10-26 at 1 52 41 pm](https://cloud.githubusercontent.com/assets/1714621/10742795/4773276a-7bec-11e5-8662-6d3095d85cd2.png)

Perhaps the comment I added from Monica Poelchau on Sept 10 lent itself to some confusion. It should not be understood from that comment that it is *always true* that when a gene model is split, the resulting genes should no longer have the same gene parent. This will be true if their CDSs don't overlap (as in the example immediately below), but it will not be true if they are isoforms (as in the example above).

Before splitting:
![screen shot 2015-10-26 at 1 57 42 pm](https://cloud.githubusercontent.com/assets/1714621/10743287/6114f98e-7bef-11e5-9af5-c7a9dc8c0d76.png)

After splitting:
![screen shot 2015-10-26 at 1 58 12 pm](https://cloud.githubusercontent.com/assets/1714621/10743295/670765e8-7bef-11e5-88fc-0a0b087a9cdf.png)


For an example of a biologically accurate representation of what I am discussing, please see image below and http://www.ncbi.nlm.nih.gov/gene/1756  Here, note that despite the fact that the two gene models I marked with the yellow arrows don't have overlapping CDS with each other, their corresponding CDS -separately- overlap with other isoforms in the region, and thus, they are all isoforms of the same gene, in this case DMD (Dystrophin).
![isoforms-1](https://cloud.githubusercontent.com/assets/1714621/10743205/d8e82eb4-7bee-11e5-9d15-550982a799a5.png)

=========

The result of merging two gene models, one of which is already an isoform of another transcript, appropriately assigns the names.
  
![screen shot 2015-10-26 at 2 00 27 pm](https://cloud.githubusercontent.com/assets/1714621/10743643/9fa1696a-7bf1-11e5-91ca-d0096b0414a2.png)

![screen shot 2015-10-26 at 2 01 15 pm](https://cloud.githubusercontent.com/assets/1714621/10743646/a5d0d258-7bf1-11e5-910c-3e90294ffd20.png)

Curiously, after modifying the gene models so that the same situation was generated (three isoforms, two of which do not overlap with each other, but their CDSs overlap with that of a third isoform), Apollo renamed all isoforms and appropriately assigned the same gene parent. 

![screen shot 2015-10-26 at 3 00 37 pm](https://cloud.githubusercontent.com/assets/1714621/10743863/0bf844b6-7bf3-11e5-821c-cb363f01652a.png)

NOTE: in the process of modifying these transcripts, I also found out that the parent gene names are not always immediately flushed out of the _Information Editor_ (see the image revealing inconsistency). A 'refresh' was necessary to update the names. 

![screen shot 2015-10-26 at 2 02 45 pm](https://cloud.githubusercontent.com/assets/1714621/10743918/6eb55a30-7bf3-11e5-856e-6d6db6975cd0.png)

@deepakunni3 we can chat more about this if you need me to clarify. I know that's a lot of notes in this comment. 


(Review time: 105 min).

**Comment by monicacecilia** [comment]
I hate to say it, but something is still not quite right here. All the issues described above are taking care of. so, hooray for that! we are almost there.

There is now a problem about naming under very specific conditions.

It happens when:  

First I:
- Dragged GB51345 into UcA area
- Corrected non-canonical splice site
- Deleted exons 2 and 3

__See gene model on the left:__
![screen shot 2015-12-10 at 8 04 08 am](https://cloud.githubusercontent.com/assets/1714621/11721177/662d40fc-9f17-11e5-9e1b-c9cabd0fee38.png)


Then, I:
- Dragged 2 isoforms of GB51346 into UcA area (see gene model on the right in figure above).
- Merged one of these to GB51345 (mentioned above)
- As a result, the name of other isoform changed, as though its provenance was the gene model above. The name indicates it is a different gene, but despite not sharing CDS the name changed to GB51345-a-00001, when it should have kept the name GB51346. 

__See the renaming on the right:__
![screenshot-](https://cloud.githubusercontent.com/assets/1714621/11721181/6b46367a-9f17-11e5-9631-f147f9bf6755.png)

HOWEVER!

If done in a different order, the name is kept as it should: 
- Drag GB51345
- Correct non-canonical splice site
- Delete exons 2 and 3
Then:
- Drag GB51346 
- Merge GB51345 and GB51346 -- notice the correct change in the name of this gene.
Then: 
- Drag a second isoform of GB51346. Note that they do not share CDS, so the name appropriately remains GB51346. 

![screen shot 2015-12-10 at 8 33 56 am](https://cloud.githubusercontent.com/assets/1714621/11721540/25c113de-9f19-11e5-9d66-2c1d7681437c.png)

(Review time: 75 min.)

**Comment by nathandunn** [comment]
Initially I thought this was a naming issue, however, it looks as though a valid gene is being deleted during the merge process even though there is a valid overlapping isoform present and a new one being created in its stead (which it does correctly).

**Comment by nathandunn** [comment]
It looks like the behavior is:
1 - given transcript A-1 (gene A) and transcripts B-1 and B-2 (gene B)
2 - when we merge the A-1 and B-1 we get A-1` (still gene A) but then B-2 is assigned to gene A as well.  
3 - handleIsoform works perfectly here and identifies that there is no actual overlap and creates another gene for B-2

So will fix step 2.

**Comment by nathandunn** [comment]
Errant code.   Implies that all transcripts . . . even if not valid isoforms . . should be moved between genes.  

```
        if (gene1 && gene2) {
            if (gene1 != gene2) {
                log.debug "Gene1 != Gene2; merging genes together"
                List<Transcript> gene2Transcripts = getTranscripts(gene2)
                for (Transcript transcript : gene2Transcripts) {
                    // moving all transcripts of gene2 to gene1, except for transcripts2 which needs to be deleted
                    if (transcript != transcript2) {
                        deleteTranscript(gene2, transcript)
                        featureService.addTranscriptToGene(gene1, transcript)
                    }
                }
                flag=true
                featureRelationshipService.deleteFeatureAndChildren(gene2)
            }
        }
```

**Comment by nathandunn** [comment]
This should be fixed.  @deepakunni3  Also fixed it in the reverse-strand case which I had overlooked.

**Comment by monicacecilia** [comment]
I think this is appropriate for me to say today: *Hallelujah!*
Great job @deepakunni3 !!
:dancer: :dancer: :dancer:
