### ISSUE TITLE
Need a "clear" selections button to support pagination and searches

### ISSUE THREAD

**Issue by strumpfe** [GMOD/Apollo#730]
The interface to select reference sequence regions for export as fasta or GFF3 has no easy mechanism to deselect/clear all items A simple "Clear selection" button would be helpful here.

![no_clear_button_in_selection_menu](https://cloud.githubusercontent.com/assets/2750489/11733158/a225d4e4-9fa2-11e5-836a-b09123b15981.png)

**Comment by nathandunn** [comment]
If you click on any "other" reference-seq selection without the command / multiple-select key it will clear the other entries. 

If there is a certain combination that this doesn't work with scenario, then please re-open.

**Comment by nathandunn** [comment]
Am re-opening with a new title.    The idea is that we are populating a "search" set, which should support search or pagination.  

- [ ] add a clear selections button
- [ ] add a show selections filter / button

**Comment by nathandunn** [comment]
<img width="588" alt="screen shot 2016-05-26 at 5 36 04 am" src="https://cloud.githubusercontent.com/assets/751274/15574699/c69acaca-2303-11e6-9d19-be25658e106a.png">
<img width="588" alt="screen shot 2016-05-26 at 5 35 56 am" src="https://cloud.githubusercontent.com/assets/751274/15574700/c6af6dc2-2303-11e6-84b2-4bce9a09e1b1.png">

**Comment by nathandunn** [comment]
FYI @monicacecilia @strumpfe   [review / thoughts when you have time](https://github.com/GMOD/Apollo/issues/730#issuecomment-221858611).  I'll try to put something on staging by the end of the week.

**Comment by nathandunn** [comment]
@deepakunni3   Do you think that this might work better if the All, Selected, Current is all on one line?    And the header would show "selected (3)" instead of the first in the list of 3 (when not in drop-down mode)?

I was thinking of a checkbox to potentially deselect a scaffold might be good, or having an add-to-pile button.  

Anyway, probably over-thinking it.  It was pretty obvious what was going on once I started playing with it.  I think the first comment (changing the header to "selected" and somehow moving them all to the same line) would be good.  Can talk about it more in a bit.

**Comment by deepakunni3** [comment]
@nathandunn Yes, I agree that replacing the 'selected' button with a dropdown would be more efficient use of the real estate. Actually that was the original plan but had some issues with getting the widgets to work as expected. 
- I tried Gwt-bootstrap dropdown and the problem is that dropdown doesn't have scrollbar and if the dropdown is long enough we see it overflow below the page.
- I tried GWT CellList which has a scrollbar but it looked really out of place, in terms of appearance.

I also tried adding a button with each entry in the Select box that would allow it to be removed from the selection list but it only messed up the display within the select box.

We can discuss this more today.

**Comment by monicacecilia** [comment]
- [ ] Remove button that shows a selected group, when only one has been selected. 
- [ ] Remove 'None' button, in favor of 'clear symbol' button.

**Comment by nathandunn** [comment]
[ ] users / groups selection popup is hidden

**Comment by nathandunn** [comment]
@monicacecilia  Should this be closed or are we waiting for the "hover" for this?

**Comment by monicacecilia** [comment]
Confirmed that users are able to: 
- select multiple reference sequences, continuous or not, and across different pages of the listed sequences.
- de-select one or more sequences from a group by command/apple key + click.
- remove all selections using "clear" button.
- downloading data from selected sequences.
This gets two dancers! 💃  💃
