### ISSUE TITLE
sync to 1.12-X version of JBrowse

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#744]
https://github.com/GMOD/jbrowse/releases/tag/1.12.0-release

**Comment by nathandunn** [comment]
FYI @monicacecilia

**Comment by monicacecilia** [comment]
:+1:

**Comment by cmdcolin** [comment]
In general I think upgrading is fine, although the new menu format is kind of awkward in my opinion. I would use the classicMenu and hideGenomeOptions config variables to keep our current menu format

**Comment by nathandunn** [comment]
K . . thanks

**Comment by cmdcolin** [comment]
Also, currently there is the assumption that the "version" was  called "dev" on the git clone in the build.xml. 


The version was renamed to 1.x.x in the 1.12 release

Instead of switching from dev to 1.x.x in the file, it would be good to populate the src/JBrowse/package.json with the version number properly.

**Comment by nathandunn** [comment]
Closed by #935.
