### ISSUE TITLE
genomic insertion coordinates: start is greater than end in gff3 output from Reference Sequence tab

### ISSUE THREAD

**Issue by mpoelchau** [GMOD/Apollo#747]
Hi there,

Another very very minor bug report. We've been working with some sequence modification features, and I've used the 'Reference Sequence -> Save track data' option to export gff3s for testing purposes. I noticed that for insertions, the start and end coordinates don't follow the gff3 spec - the start is greater than the end (see snippet below from the Apollo 2 demo instance). The output from the regular gff3 export is fine in Apollo 1. (The sequence modification features didn't export in Apollo 2, but I'll create a separate bug report for that :)).  
## sequence-region Group1.1 1 1382403

Group1.1        .       substitution    433181  433181  .       +       .       ID=36154e91-dc21-4245-bac9-4c27d214123b;residues=A;seq=A
Group1.1        .       substitution    433331  433331  .       +       .       ID=b12f9bb2-e385-437e-a713-e0892896e629;residues=A;seq=A
### 

Group1.1        .       insertion       725121  725120  .       +       .       ID=728d4df4-64b9-4e36-bfda-c7de8f77fd89;residues=ATGCT;seq=ATGCT
Group1.1        .       deletion        725139  725143  .       +       .       ID=d5b1c424-d378-4a96-b25e-9b906d1b8e98;residues=CCCCC;seq=CCCCC
### 

Group1.1        .       substitution    725155  725159  .       +       .       ID=85d31956-b0e5-42c1-bba3-1c536e15c65c;residues=ATGTG;seq=ATGTG

**Comment by nathandunn** [comment]
lower priority.   The code itself looks correct.  For an insertion, if the start and end are set to equals, they are both increased by one, otherwise only one is.   Not sure what would be causing that use-case.

https://github.com/GMOD/Apollo/blob/master/grails-app/services/org/bbop/apollo/Gff3HandlerService.groovy#L219-L220

**Comment by deepakunni3** [comment]
The code that handles export via 'Reference Track -> Save Track Data' operation is different from Gff3HandlerService. 

It looks like its being handled by `JBrowse.View.Export.GFF3`.

**Comment by cmdcolin** [comment]
It is kind of weird representing insertions in 1-base coordinates like GFF so you get this weird special case for insertions that is not accounted for by the default exporter https://www.biostars.org/p/84686/

if (type=SNV){start=start+1; end=end;}
if (type=DEL){start=start+1; end=end;}
if (type=INS){start=start; end=end+1;}


Since the 0-base exporter in BED format doesn't need conversion, it is almost better to just use BED only, but that doesn't include attributes or even indicate that these are insertions/deletions.

I'd recommend a pull request to jbrowse to add ability to override exporters

https://github.com/GMOD/jbrowse/blob/master/src/JBrowse/View/Track/_ExportMixin.js#L281
^^ That line shows that it only looks in the JBrowse namespace for exporters

Fixing custom exporters upstream would make any custom work on WA side easier

**Comment by cmdcolin** [comment]
Note that the #840 fixes the export of residues so that particular issue is taken care of

**Comment by cmdcolin** [comment]
Also note that this is related to https://github.com/GMOD/Apollo/issues/4 which says that really the "Save track data" should export sequence data, but it exports the sequence alterations because it swaps the sequence store with the alteration store at startup. We could alternately fix this by just saying to change this behavior in this issue to just use #4  behavior instead

**Comment by cmdcolin** [comment]
Opened PR for jbrowse here https://github.com/GMOD/jbrowse/pull/682

**Comment by nathandunn** [comment]
@cmdcolin   So this one is ready?  I agree with you for the JBrowse pull request.   I want to double-check with @enuggetry , but I don't see any issue.

**Comment by cmdcolin** [comment]
Not really fixed here. If JBrowse PR goes through, we can add a fix, but then we also have to upgrade jbrowse versions in WA.

There are some alternative workarounds. We can even remove the Save track data button to reduce confusion.

**Comment by nathandunn** [comment]
Probably not worth that.  I'm going to move it to 2.0.3 and then we can bump the Apollo version then (1.12.1?).  We can leave the save button in there for now with this bug.

**Comment by monicacecilia** [comment]
Since we are currently working from JBrowsev1.12.1 this has been fixed (with 99% certainty) in v2.0.2
Merge to 1.12.1 occurred Feb-1-2016.

**Comment by nathandunn** [comment]
@monicacecilia types: @mpoelchau we think this is fixed now. Please let us know if you come across the issue again.
