### ISSUE TITLE
Persistent screen over 'Links to this Location' popup

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#778]
When a user without admin privileges clicks on the 'Links' button, a semi-transparent screen appears over the popup and the main window. The entire window is disabled and the only solution is to refresh.

Sumitted by @adnguyen999

<img width="748" alt="screen shot 2016-01-14 at 1 43 16 pm" src="https://cloud.githubusercontent.com/assets/1714621/12338543/f260349e-bac4-11e5-8d7f-a8ce863d2b74.png">

**Comment by nathandunn** [comment]
Related to #746

**Comment by nathandunn** [comment]
@deepakunni3  I ran into this problem on a few other pages.  I *think* the problem is that there is either a css namespace collision or library problem.   I would see what happens when you add / remove tabs as either an admin or user.   

I did have a fix for this in other places (see all of the modals in the MainPanel  . . like the edit user password popup).   Hopefully we can fix it another way, though.

**Comment by monicacecilia** [comment]
Meta-reference decoder at #768

**Comment by monicacecilia** [comment]
It's fixed, so I'm closing... but don't forget #746 
does not get a dancer. :person_with_pouting_face:

**Comment by nathandunn** [comment]
Did you see anything in #746?   @deepakunni3 discovered that updating the library fixed a lot of this, as well.  I think we can probably close both.  

Nathan
