### ISSUE TITLE
test migration 2.0.0 -> 2.0.2 && 2.0.1 -> 2.0.2

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#848]
Need to make sure that we can properly migrate between the two

**Comment by cmdcolin** [comment]
First tried the following 

(a) booting up a 2.0.1 instance
(b) initializing the database for 2.0.1
(c) checking out master/2.0.2
(d) running  `grails dbm-gorm-diff changelog-2.0.2.groovy -add`

This created a changelog with some elements in it, but most didn't make sense (here is what it outputted for changelog-2.0.2.groovy - http://pastebin.com/3pduBDMM).

I was gonna test out regular dbm-diff but I was getting some trouble with it, but that did seem promising since I think I heard that the gorm-diff can make false positives

**Comment by cmdcolin** [comment]
I guess in the abstract I wonder if this release needs a changelog. Not really any database changes were made except the index added to the featureevent table for uniqueName

Should we manually create the changelog file for that?

**Comment by nathandunn** [comment]
The changelog can be pretty minimal (unlike 2.0.1).  The two things I *KNOW* we need to change are:

1 - FeatureLocation.length (the property that you added)
2 - Adding the index I added.   

Basically, if those two don't exist they should be added, though there might be other stuff that needs to be there.

**Comment by cmdcolin** [comment]
Sorry to be a bug here but featurelocation.length is a derived property, it does not change the database.  I think only real thing that changes is adding the index

**Comment by nathandunn** [comment]
So it is.  Yeah, this will be pretty easy then.   Basically, just follow the bottom of the 2.0.1 script (which accounts for the MySQL namespace) in order to add the proper index.   We just need to make sure we test:

- de novo -> 2.0.2 (should just work)
- 2.0.0 -> 2.0.2
- 2.0.1 -> 2.0.2

The 2.0.0 -> 2.0.2 is the only one that might be difficult, but I don’t anticipate any problem.

**Comment by nathandunn** [comment]
POSTGRESQL
- [ ] de novo -> 2.0.2
- [ ] 2.0.0 -> 2.0.2
- [ ] 2.0.1 -> 2.0.2

MYSQL 
- [ ] de novo -> 2.0.2
- [ ] 2.0.0 -> 2.0.2
- [ ] 2.0.1 -> 2.0.2
