### ISSUE TITLE
Why are these buttons clickable?

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#918]
Is there a plan for these buttons to go somewhere? 
Else, they should not be clickable. 
These buttons are found on Report::Annotator

![screen shot 2016-03-03 at 6 05 44 pm](https://cloud.githubusercontent.com/assets/1714621/13515968/b321d7c0-e16a-11e5-9e51-b0f93c4787d8.png)

**Comment by nathandunn** [comment]
Didn't realize they were buttons .. should be an easy fix.

**Comment by nathandunn** [comment]
Oh . . I think that these were fixed in 2.0.2.  Here is a screenshot from demo:

<img width="1178" alt="screen shot 2016-03-08 at 11 16 05 am" src="https://cloud.githubusercontent.com/assets/751274/13613031/2f459ea6-e51f-11e5-843b-3328204a1239.png">

Still could be prettier, but definitely not buttons.
