### ISSUE TITLE
Alternate formatting for usernames?

### ISSUE THREAD

**Issue by childers** [GMOD/Apollo#933]
Is there any option to support an alternate format for the Apollo2 username? Do you have any code that depends on the username being a qualified email address vs having the email as part of the users record?

We are planning to handle user registration and account creation through our own framework, and we are planning to use Apollo2 IDs based on the user names in our authentication system (one fewer username to remember is always nice).  To fit within the Apollo2 paradigm of email based Ids, we had thought to use the format <USERNAME>@i5k.workspace, where <USERNAME> is the username in our SSO authentication system. I don't like the idea of making an ID that looks like an email but isn't real, but that is better than using a fake email address for a domain that doesn't exist in our production environment, and I can't issue email addresses for our users. In testing this, I realized that you correctly check that the email address uses a valid TLD. This is a really good thing for validation, but stops my workflow completely. 

One fundamental concern is that email addresses are not inherently stable, and can change for several reasons: as affiliations change, as a result of a change of name, or sometimes service updates can change an email address without any external reason.  Having an outdated Apollo2 account because you got a new job would be a pain.  While we can always manually update the database, having a user account system where that can be changed by the user is preferable, and not possible with the way it's set up now.

We actually implemented email addresses for Apollo1 user names a while ago, and one of the most frequently asked questions we get (especially from our power users) is if they could change their login back to the old "not email" style.

For me the single largest issue is our impending migration. Handling ownership of features for users that missed our initial migration window but come later. For our migration, unless we get 100% of our users to claim their accounts, we're going to have orphan Apollo1 users. I can't omit their annotations, I don't have a valid email address that I can assign to them. My current workflow is to create a locked account, which can be connected to the user if they ever come back, but won't get lost.  All of this is so much more complicated when working in a system that is not between annotation cycles.

Another interesting scenario we have seen is supporting users that want a 'group' account for their students or staff to use together.  We've had more than a few requests for this type of account, and it is a reasonable request if there is going to ultimately be one supervisor responsible for all the annotations of multiple people. This could be handled by the concept of a different type of group, that had it's own mechanisms for permission management. We're investigating different ways to support these user requests.

**Comment by nathandunn** [comment]
The username is a string that validates to “email” strings, but that is a [one-line change in the constraints](https://github.com/GMOD/Apollo/blob/master/grails-app/domain/org/bbop/apollo/User.groovy#L28).

This could be made configurable.   Emails are a unique ID, a way to contact a user, and something a user will have memorized (is there truly well-supported alternate to this, we could also implement that instead?).  I think that one of the hallmarks of curation is being able to both contact and identify your curators in order to create a paper trail.     A couple of workarounds:

- You (as admin) can change the username / email as admin at any time.   
- We can also add the mechanism for user’s to change their own email / username.   

WRT to ownership of features and migration, I would create emails in the new system (or not emails if need be), convert the user info the old system (which has to be done anyway) and then perform the migration.  We might need to churn on this a bit, but it should be pretty tractable. 

I’m very curious about the "group” accounts, if there are better ways to support that then let me know.   Individual users logging into the same account is very bad idea and defeats the purpose of tracking curator efforts, so I like the approach you are looking at alternate permissions to large groups.   

- I think what you really need is a report by group that would allow a user with write (or admin) permissions to quickly go through and set the “status” for each annotation.  

I'm going to close this (but anyone feel free to comment).  I think that there are two or three new issues that can come out of this, however.

**Comment by childers** [comment]
Thanks for pointing me to the user constraints, and for the discussion. There are a lot of discussions about whether or not to use emails as a login name, and I'm glad we can support the use case that works within our framework.

I also agree that there were more ideas in this that could be teased out and developed.  Looking forward to discussing it more.

Thanks!
